version: "2"
linters:
  enable:
    - bodyclose
    - godox
    - nakedret
    - predeclared
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofumpt
