//go:build !cmd_go_bootstrap

package openssl

import (
	"runtime"
	"unsafe"

	"github.com/microsoft/go/pkg/openssl/internal/ossl"
)

// SupportsDSA returns true if the OpenSSL library supports DSA.
func SupportsDSA() bool {
	ctx, err := ossl.EVP_PKEY_CTX_new_id(ossl.EVP_PKEY_DSA, nil)
	if err != nil {
		return false
	}
	ossl.EVP_PKEY_CTX_free(ctx)
	return true
}

// DSAParameters contains the DSA parameters.
type DSAParameters struct {
	P, Q, G BigInt
}

// PrivateKeyDSA represents a DSA private key.
type PrivateKeyDSA struct {
	DSAParameters
	X, Y BigInt

	// _pkey MUST NOT be accessed directly. Instead, use the withKey method.
	_pkey ossl.EVP_PKEY_PTR
}

func (k *PrivateKeyDSA) finalize() {
	ossl.EVP_PKEY_free(k._pkey)
}

func (k *PrivateKeyDSA) withKey(f func(ossl.EVP_PKEY_PTR) error) error {
	defer runtime.KeepAlive(k)
	return f(k._pkey)
}

// PublicKeyDSA represents a DSA public key.
type PublicKeyDSA struct {
	DSAParameters
	Y BigInt

	// _pkey MUST NOT be accessed directly. Instead, use the withKey method.
	_pkey ossl.EVP_PKEY_PTR
}

func (k *PublicKeyDSA) finalize() {
	ossl.EVP_PKEY_free(k._pkey)
}

func (k *PublicKeyDSA) withKey(f func(ossl.EVP_PKEY_PTR) error) error {
	defer runtime.KeepAlive(k)
	return f(k._pkey)
}

// GenerateParametersDSA generates a set of DSA parameters.
func GenerateParametersDSA(l, n int) (DSAParameters, error) {
	// The DSA parameters are generated by creating a new DSA key and
	// extracting the domain parameters from it.

	// Generate a new DSA key context and set the known parameters.
	ctx, err := ossl.EVP_PKEY_CTX_new_id(ossl.EVP_PKEY_DSA, nil)
	if err != nil {
		return DSAParameters{}, err
	}
	defer ossl.EVP_PKEY_CTX_free(ctx)
	if _, err := ossl.EVP_PKEY_paramgen_init(ctx); err != nil {
		return DSAParameters{}, err
	}
	if _, err := ossl.EVP_PKEY_CTX_ctrl(ctx, ossl.EVP_PKEY_DSA, -1, ossl.EVP_PKEY_CTRL_DSA_PARAMGEN_BITS, int32(l), nil); err != nil {
		return DSAParameters{}, err
	}
	if _, err := ossl.EVP_PKEY_CTX_ctrl(ctx, ossl.EVP_PKEY_DSA, -1, ossl.EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS, int32(n), nil); err != nil {
		return DSAParameters{}, err
	}
	var pkey ossl.EVP_PKEY_PTR
	if _, err := ossl.EVP_PKEY_paramgen(ctx, &pkey); err != nil {
		return DSAParameters{}, err
	}
	defer ossl.EVP_PKEY_free(pkey)

	// Extract the domain parameters from the generated key.
	var p, q, g ossl.BIGNUM_PTR
	switch vMajor {
	case 1:
		dsa := getDSA(pkey)
		ossl.DSA_get0_pqg(dsa, &p, &q, &g)
	case 3:
		defer func() {
			ossl.BN_free(p)
			ossl.BN_free(q)
			ossl.BN_free(g)
		}()
		if _, err := ossl.EVP_PKEY_get_bn_param(pkey, _OSSL_PKEY_PARAM_FFC_P.ptr(), &p); err != nil {
			return DSAParameters{}, err
		}
		if _, err := ossl.EVP_PKEY_get_bn_param(pkey, _OSSL_PKEY_PARAM_FFC_Q.ptr(), &q); err != nil {
			return DSAParameters{}, err
		}
		if _, err := ossl.EVP_PKEY_get_bn_param(pkey, _OSSL_PKEY_PARAM_FFC_G.ptr(), &g); err != nil {
			return DSAParameters{}, err
		}
	default:
		panic(errUnsupportedVersion())
	}

	return DSAParameters{
		P: bnToBig(p),
		Q: bnToBig(q),
		G: bnToBig(g),
	}, nil
}

// NewPrivateKeyDSA creates a new DSA private key from the given parameters.
func NewPrivateKeyDSA(params DSAParameters, x, y BigInt) (*PrivateKeyDSA, error) {
	if x == nil || y == nil {
		panic("x and y must not be nil")
	}
	pkey, err := newDSA(params, x, y)
	if err != nil {
		return nil, err
	}
	k := &PrivateKeyDSA{params, x, y, pkey}
	runtime.SetFinalizer(k, (*PrivateKeyDSA).finalize)
	return k, nil
}

// NewPublicKeyDSA creates a new DSA public key from the given parameters.
func NewPublicKeyDSA(params DSAParameters, y BigInt) (*PublicKeyDSA, error) {
	if y == nil {
		panic("y must not be nil")
	}
	pkey, err := newDSA(params, nil, y)
	if err != nil {
		return nil, err
	}
	k := &PublicKeyDSA{params, y, pkey}
	runtime.SetFinalizer(k, (*PublicKeyDSA).finalize)
	return k, nil
}

// GenerateKeyDSA generates a new private DSA key using the given parameters.
func GenerateKeyDSA(params DSAParameters) (x, y BigInt, err error) {
	pkey, err := newDSA(params, nil, nil)
	if err != nil {
		return nil, nil, err
	}
	defer ossl.EVP_PKEY_free(pkey)
	var bx, by ossl.BIGNUM_PTR
	switch vMajor {
	case 1:
		dsa := getDSA(pkey)
		ossl.DSA_get0_key(dsa, &by, &bx)
	case 3:
		defer func() {
			ossl.BN_clear_free(bx)
			ossl.BN_free(by)
		}()
		if _, err := ossl.EVP_PKEY_get_bn_param(pkey, _OSSL_PKEY_PARAM_PUB_KEY.ptr(), &by); err != nil {
			return nil, nil, err
		}
		if _, err := ossl.EVP_PKEY_get_bn_param(pkey, _OSSL_PKEY_PARAM_PRIV_KEY.ptr(), &bx); err != nil {
			return nil, nil, err
		}
	default:
		panic(errUnsupportedVersion())
	}
	return bnToBig(bx), bnToBig(by), nil
}

// SignDSA signs a hash (which should be the result of hashing a larger message).
func SignDSA(priv *PrivateKeyDSA, hash []byte) ([]byte, error) {
	return evpSign(priv.withKey, 0, 0, 0, hash)
}

// VerifyDSA verifiessig using the public key, pub.
func VerifyDSA(pub *PublicKeyDSA, hash []byte, sig []byte) bool {
	return evpVerify(pub.withKey, 0, 0, 0, sig, hash) == nil
}

func newDSA(params DSAParameters, x, y BigInt) (ossl.EVP_PKEY_PTR, error) {
	switch vMajor {
	case 1:
		return newDSA1(params, x, y)
	case 3:
		return newDSA3(params, x, y)
	default:
		panic(errUnsupportedVersion())
	}
}

func newDSA1(params DSAParameters, x, y BigInt) (pkey ossl.EVP_PKEY_PTR, err error) {
	checkMajorVersion(1)

	dsa, err := ossl.DSA_new()
	if err != nil {
		return nil, err
	}
	defer func() {
		if pkey == nil {
			ossl.DSA_free(dsa)
		}
	}()
	// No need to check for errors here, DSA_set0_* functions will fail
	// if the BNs are NULL and we will free non-NULL BNs in the error handling.
	p, _ := bigToBN(params.P)
	q, _ := bigToBN(params.Q)
	g, _ := bigToBN(params.G)
	if _, err := ossl.DSA_set0_pqg(dsa, p, q, g); err != nil {
		ossl.BN_free(p)
		ossl.BN_free(q)
		ossl.BN_free(g)
		return nil, err
	}
	if y != nil {
		pub, _ := bigToBN(y)
		priv, _ := bigToBN(x)
		if _, err := ossl.DSA_set0_key(dsa, pub, priv); err != nil {
			ossl.BN_free(pub)
			ossl.BN_clear_free(priv)
			return nil, err
		}
	} else {
		if _, err := ossl.DSA_generate_key(dsa); err != nil {
			return nil, err
		}
	}
	pkey, err = ossl.EVP_PKEY_new()
	if err != nil {
		return nil, err
	}
	if _, err := ossl.EVP_PKEY_assign(pkey, ossl.EVP_PKEY_DSA, unsafe.Pointer(dsa)); err != nil {
		ossl.EVP_PKEY_free(pkey)
		return nil, err
	}
	return pkey, nil
}

func newDSA3(params DSAParameters, x, y BigInt) (ossl.EVP_PKEY_PTR, error) {
	checkMajorVersion(3)

	bld, err := newParamBuilder()
	if err != nil {
		return nil, err
	}
	defer bld.finalize()

	bld.addBigInt(_OSSL_PKEY_PARAM_FFC_P, params.P, false)
	bld.addBigInt(_OSSL_PKEY_PARAM_FFC_Q, params.Q, false)
	bld.addBigInt(_OSSL_PKEY_PARAM_FFC_G, params.G, false)
	selection := int32(ossl.EVP_PKEY_KEYPAIR)
	if y != nil {
		bld.addBigInt(_OSSL_PKEY_PARAM_PUB_KEY, y, false)
		if x == nil {
			selection = ossl.EVP_PKEY_PUBLIC_KEY
		}
	}
	if x != nil {
		bld.addBigInt(_OSSL_PKEY_PARAM_PRIV_KEY, x, true)
	}
	bldparams, err := bld.build()
	if err != nil {
		return nil, err
	}
	defer ossl.OSSL_PARAM_free(bldparams)
	pkey, err := newEvpFromParams(ossl.EVP_PKEY_DSA, selection, bldparams)
	if err != nil {
		return nil, err
	}
	if y != nil {
		return pkey, nil
	}
	// pkey doesn't contain the public component, but the crypto/dsa package
	// expects it to be always there. Generate a new key using pkey as domain
	// parameters placeholder.
	defer ossl.EVP_PKEY_free(pkey)
	ctx, err := ossl.EVP_PKEY_CTX_new_from_pkey(nil, pkey, nil)
	if err != nil {
		return nil, err
	}
	defer ossl.EVP_PKEY_CTX_free(ctx)
	if _, err := ossl.EVP_PKEY_keygen_init(ctx); err != nil {
		return nil, err
	}
	var gkey ossl.EVP_PKEY_PTR
	if _, err := ossl.EVP_PKEY_keygen(ctx, &gkey); err != nil {
		return nil, err
	}
	return gkey, nil
}

// getDSA returns the DSA from pkey.
// If pkey does not contain an DSA it panics.
// The returned key should not be freed.
func getDSA(pkey ossl.EVP_PKEY_PTR) ossl.DSA_PTR {
	key, err := ossl.EVP_PKEY_get0_DSA(pkey)
	if err != nil {
		panic(err)
	}
	return key
}
