#!/usr/bin/env bash

# This script generates a CodeQL configuration file that classifies paths
# based on the patches applied to a Go submodule. It identifies which files
# should be treated as part of the library and which should be excluded.
# Docs can be found at https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/troubleshooting/bugs/generated-library-code

PATCH_DIR="patches"
GO_SUBMODULE_PATH="go"
OUTPUT_FILE="CodeQL.yml"

{
  echo "# This file is auto-generated by generate-codeql-yml.sh"
  echo "path_classifiers:"
  echo "  library:"
  echo "    # Classify the upstream go submodule as a 3rd-party library"
  echo "    - \"$GO_SUBMODULE_PATH/**\""
  echo "    # Except for these Go source files which we patch)"

  # Extract unique .go paths from patches to re-include
  find "$PATCH_DIR" -type f -name "*.patch" | while read -r patch; do
    grep '^diff --git a/' "$patch" | while read -r line; do
      path=$(echo "$line" | cut -d' ' -f3 | sed 's|^a/||')

      # Re-include if:
      # - is a .go file
      # - not in src/vendor/
      # - not in src/cmd/vendor/
      # - not a *_test.go file
      # - not in any testdata/ folder
      if [[ "$path" == *.go &&
            "$path" != src/vendor/* &&
            "$path" != src/cmd/vendor/* &&
            "$path" != */testdata/* &&
            "$path" != *_test.go ]]; then
        echo "    - exclude: $path"
      fi
    done
  done | sort -u
} > "$OUTPUT_FILE"

echo "✅ Generated $OUTPUT_FILE"
