// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build msgostd || cmd_go_bootstrap

package sha256

import (
	fallback "crypto/internal/fips140/sha256"
	"hash"
)

type fipsHash = fallback.Digest

func initFallback256() *fipsHash { return fallback.New() }

func initFallback224() *fipsHash { return fallback.New224() }

func New() *Hash { return newHash(hashSHA256) }

func New224() *Hash { return newHash(hashSHA224) }

// Unwrap returns the selected hash implementation.
func Unwrap(h *Hash) hash.Hash { return h.unwrap() }
