// Copyright (c) Microsoft Corporation.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/tabwriter"
)

var docPath = flag.String("path", filepath.Join("eng", "doc", "CrossPlatformCryptography.md"), "Path to CrossPlatformCryptography.md")

var useStdout = flag.Bool("stdout", false, "Write to stdout instead of file")

func main() {
	flag.Parse()

	if err := write(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func write() error {
	s, err := generate()
	if err != nil {
		return fmt.Errorf("failed to generate document: %v", err)
	}

	if *useStdout {
		fmt.Print(s)
		return nil
	}
	return os.WriteFile(*docPath, []byte(s), 0o644)
}

func generate() (string, error) {
	if err := validate(doc); err != nil {
		return "", fmt.Errorf("validation failed: %v", err)
	}

	var s strings.Builder

	fmt.Fprintln(&s, "<!-- This file is generated by eng/_util/cmd/updatecryptodocs. DO NOT EDIT. -->")
	fmt.Fprintln(&s)
	fmt.Fprintf(&s, "%s", header)

	for _, section := range doc.Sections {
		printSection(&s, section, 2)
	}
	return s.String(), nil
}

func printSection(w io.Writer, section Section, level int) {
	fmt.Fprintf(w, "\n%s %s\n\n", strings.Repeat("#", level), section.Title)

	// Filter packages
	var validPackages []string
	for _, pkg := range section.Packages {
		if strings.Contains(pkg, "/") || strings.Contains(pkg, ".") {
			validPackages = append(validPackages, pkg)
		}
	}

	if len(validPackages) > 0 {
		fmt.Fprintln(w, "This section includes the following packages:")
		fmt.Fprintln(w)
		for _, pkg := range validPackages {
			if strings.HasPrefix(pkg, "crypto/") {
				fmt.Fprintf(w, "- [%s](https://pkg.go.dev/%s)\n", pkg, pkg)
			} else if strings.HasPrefix(pkg, "golang.org/") {
				fmt.Fprintf(w, "- [%s](https://pkg.go.dev/%s)\n", pkg, pkg)
			} else {
				// Fallback
				fmt.Fprintf(w, "- %s\n", pkg)
			}
		}
		fmt.Fprintln(w)
	}

	// Prepend version requirements to description if present
	var versionSentences []string
	if section.MinGoVersion != "" {
		versionSentences = append(versionSentences, fmt.Sprintf("%s is available starting from the Microsoft build of Go %s.", section.Title, section.MinGoVersion))
	}
	if len(versionSentences) > 0 {
		fmt.Fprintln(w, strings.Join(versionSentences, " "))
		fmt.Fprintln(w)
	}
	if section.Description != "" {
		fmt.Fprintln(w, section.Description)
		fmt.Fprintln(w)
	}
	for _, para := range section.DescriptionParagraphs {
		fmt.Fprintln(w, para)
		fmt.Fprintln(w)
	}

	// Subsections list
	if len(section.Subsections) > 0 {
		if section.Description == "" && len(section.DescriptionParagraphs) == 0 {
			fmt.Fprintln(w, "This section includes the following subsections:")
			fmt.Fprintln(w)
		}
		for _, sub := range section.Subsections {
			// Generate anchor link
			anchor := strings.ToLower(sub.Title)
			anchor = strings.ReplaceAll(anchor, " ", "-")
			anchor = strings.ReplaceAll(anchor, "(", "")
			anchor = strings.ReplaceAll(anchor, ")", "")

			title := sub.Title
			if sub.ShortTitle != "" {
				title = sub.ShortTitle
			}
			fmt.Fprintf(w, "- [%s](#%s)\n", title, anchor)

		}
	}

	if len(section.Items) > 0 {
		printTable(w, section)
	}

	if section.Footer != "" {
		fmt.Fprintf(w, "\n%s\n", section.Footer)
	}
	for _, line := range section.FooterParagraphs {
		fmt.Fprintf(w, "\n%s\n", line)
	}

	for _, sub := range section.Subsections {
		printSection(w, sub, level+1)
	}
}

func printTable(w io.Writer, section Section) {
	colHeader := section.ColumnHeader
	if colHeader == "" {
		colHeader = "Algorithm" // Default
	}

	var wipTable strings.Builder
	tw := tabwriter.NewWriter(&wipTable, 0, 0, 1, ' ', 0)
	platforms := strings.Join(SupportedPlatforms, "\t|\t")
	platforms = strings.Replace(platforms, "windows", "Windows", 1)
	platforms = strings.Replace(platforms, "linux", "Linux", 1)
	platforms = strings.Replace(platforms, "macos", "macOS", 1)
	fmt.Fprintf(tw, "|\t%s\t|\t%s\t|\n", colHeader, platforms)

	// We skip the "| --- | --- | etc." row for now. We need to know the actual
	// column lengths to put in the proper number of dashes (for raw source
	// readability). So, we need to figure it out first and inject it later.
	// fmt.Fprintf(tw, "|\t---\t|\t---\t|\t---\t|\t---\t|\n")

	// Collect footnotes
	footnotes := make(map[string]int)
	nextFootnote := 1

	// Pre-populate from section.Footnotes
	for _, note := range section.Footnotes {
		if _, exists := footnotes[note]; !exists {
			footnotes[note] = nextFootnote
			nextFootnote++
		}
	}

	// Helper to get footnote indices
	getFootnotes := func(notes []string) string {
		if len(notes) == 0 {
			return ""
		}
		var indices []int
		for _, note := range notes {
			idx, exists := footnotes[note]
			if !exists {
				idx = nextFootnote
				footnotes[note] = idx
				nextFootnote++
			}
			indices = append(indices, idx)
		}
		sort.Ints(indices)
		strs := make([]string, len(indices))
		for i, idx := range indices {
			strs[i] = fmt.Sprintf("%d", idx)
		}
		return fmt.Sprintf("<sup>%s</sup>", strings.Join(strs, ","))
	}

	for _, item := range section.Items {
		name := item.Name

		itemNotes := item.Notes
		if item.MinGoVersion != "" {
			note := fmt.Sprintf("Available starting in the Microsoft build of Go %s.", item.MinGoVersion)
			itemNotes = append([]string{note}, itemNotes...)
		}

		nameNotes := getFootnotes(itemNotes)

		row := []string{name + nameNotes}

		for _, platform := range SupportedPlatforms {
			status := item.Platforms.Get(platform)
			symbol := ""
			switch status.Supported {
			case Supported:
				symbol = "✔️"
			case NotSupported:
				symbol = "❌️"
			case Warn:
				symbol = "⚠️"
			case N_A:
				symbol = "N/A"
			default:
				// Should not happen due to prior validation
				panic(fmt.Sprintf("unexpected status %q", status.Supported))
			}

			statusNotes := status.Notes
			// Prepend version notes in preferred order: minGoVersion, minOpenSSLVersion, minMacOSVersion
			var versionNotes []string
			if status.MinGoVersion != "" {
				versionNotes = append(versionNotes, fmt.Sprintf("Available starting in the Microsoft build of Go %s.", status.MinGoVersion))
			}
			if status.MinVersion != "" {
				switch platform {
				case "windows":
					versionNotes = append(versionNotes, fmt.Sprintf("Requires Windows %s or later.", status.MinVersion))
				case "linux":
					versionNotes = append(versionNotes, fmt.Sprintf("Requires OpenSSL %s or later.", status.MinVersion))
				case "macos":
					versionNotes = append(versionNotes, fmt.Sprintf("Requires macOS %s or later.", status.MinVersion))
				default:
					panic("unknown platform" + platform)
				}
			}
			// Remove duplicates from notes
			filtered := []string{}
			for _, n := range statusNotes {
				duplicate := false
				for _, vn := range versionNotes {
					if n == vn {
						duplicate = true
						break
					}
				}
				if !duplicate {
					filtered = append(filtered, n)
				}
			}
			statusNotes = append(versionNotes, filtered...)

			notes := getFootnotes(statusNotes)
			row = append(row, symbol+notes)
		}

		fmt.Fprintf(tw, "|\t%s\t|\t%s\t|\t%s\t|\t%s\t|\n", row[0], row[1], row[2], row[3])
	}

	err := tw.Flush()
	if err != nil {
		panic(err)
	}

	ts := wipTable.String()
	// Now, inject the separator line with proper dash lengths.
	rows := strings.Split(ts, "\n")
	firstRow := rows[0]
	fmt.Fprintf(w, "%s\n", firstRow)
	cells := strings.Split(firstRow, "|")
	// Ignore the first and last: empty strings.
	// We expect "| <label> | <label> | ... |"
	fmt.Fprintf(w, "|")
	for i := 1; i < len(cells)-1; i++ {
		fmt.Fprintf(w, " %s |", strings.Repeat("-", len(cells[i])-2))
	}
	for _, remainingRow := range rows[1:] {
		fmt.Fprintf(w, "\n%s", remainingRow)
	}

	// Print footnotes
	// Sort by index
	sortedNotes := make([]string, len(footnotes))
	for note, idx := range footnotes {
		sortedNotes[idx-1] = note
	}

	for i, note := range sortedNotes {
		fmt.Fprintf(w, "\n<sup>%d</sup>%s\n", i+1, note)
	}
}

func validate(doc Document) error {
	for _, section := range doc.Sections {
		if err := validateSection(section); err != nil {
			return err
		}
	}
	return nil
}

func validateSection(section Section) error {
	if section.Title == "" {
		return fmt.Errorf("section missing title")
	}

	seenNames := make(map[string]bool)

	for i := range section.Items {
		item := &section.Items[i]
		if item.Name == "" {
			return fmt.Errorf("item missing name in section %q", section.Title)
		}
		if seenNames[item.Name] {
			return fmt.Errorf("duplicate item name %q in section %q", item.Name, section.Title)
		}
		seenNames[item.Name] = true
		for _, p := range SupportedPlatforms {
			status := item.Platforms.Get(p)
			switch status.Supported {
			case Supported, NotSupported, Warn, N_A:
				// ok
			default:
				return fmt.Errorf("invalid supported status %q for item %q on platform %q", status.Supported, item.Name, p)
			}
		}

		// Check for notes common to all platforms
		noteCounts := make(map[string]int)
		platforms := SupportedPlatforms
		for _, p := range platforms {
			status := item.Platforms.Get(p)
			for _, note := range status.Notes {
				noteCounts[note]++
			}
		}

		for note, count := range noteCounts {
			if count == len(platforms) {
				return fmt.Errorf("note %q appears in all platforms for item %q; move it to the item level", note, item.Name)
			}
		}
	}
	for _, sub := range section.Subsections {
		if err := validateSection(sub); err != nil {
			return err
		}
	}
	return nil
}
