parameters:
  # [] of { os, arch, config }
  builders: []

jobs:
  - ${{ each builder in parameters.builders }}:
    - ${{ if eq(builder.os, 'linux' ) }}:
      - template: run-linux-job.yml
        parameters:
          builder: ${{ builder }}
