# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

parameters:
  # [] of { os, arch, config }
  builders: []

jobs:
  - ${{ each builder in parameters.builders }}:
    - ${{ if eq(builder.os, 'linux' ) }}:
      - template: run-linux-job.yml
        parameters:
          builder: ${{ builder }}

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - template: sign-job.yml
      parameters:
        # Make the signing job depend on and sign each buildandpack builder. This lets us start the
        # lengthy tasks of signing and testing in parallel. The publish stage waits for both.
        builders:
          - ${{ each builder in parameters.builders }}:
            - ${{ if eq(builder.config, 'buildandpack') }}:
              - ${{ builder }}
