# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

parameters:
  # { os, arch, config }
  builder: {}

jobs:
  - job: ${{ parameters.builder.os }}_${{ parameters.builder.arch }}_${{ parameters.builder.config }}
    pool:
      # The VM image of the Docker host. This doesn't need to match the container image, but it may
      # give slightly better coverage by matching the kernel version.
      vmImage: ubuntu-18.04
    # The image used for the container this job runs in.
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20210223192210-047508b
    workspace:
      clean: all
    steps:
      - template: checkout-unix-task.yml

      - script: |
          set -ex

          . microsoft/init-stage0.sh
          "$stage0_dir/go/bin/go" run microsoft/run-builder.go \
            -builder '${{ parameters.builder.os }}-${{ parameters.builder.arch }}-${{ parameters.builder.config }}'
        displayName: Run ${{ parameters.builder.config }}

      - ${{ if eq(parameters.builder.config, 'buildandpack' ) }}:
        - publish: microsoft/artifacts/bin
          artifact: Binaries ${{ parameters.builder.os }}_${{ parameters.builder.arch }}_${{ parameters.builder.config }}
          displayName: Pipeline publish
          condition: succeededOrFailed()
