// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build msgostd || cmd_go_bootstrap

package rsa

import (
	"crypto/internal/fips140/bigmod"
	fallback "crypto/internal/fips140/rsa"
	"errors"
	"math/big"
)

type fipsPublicKey = fallback.PublicKey
type fipsPrivateKey = fallback.PrivateKey

// GeneratedFIPSKey returns the validated Go key when k was generated by the Go
// implementation, or nil when it was generated by a native implementation.
// It does not import or validate a native key.
func GeneratedFIPSKey(k GeneratedKey) *fallback.PrivateKey {
	return k.fips
}

func newFallbackPublicKey(N []byte, e int) (*fipsPublicKey, error) {
	n, err := bigmod.NewModulus(N)
	if err != nil {
		return nil, err
	}
	return &fallback.PublicKey{N: n, E: e}, nil
}

func newFallbackPrivateKey(k *PrivateKey) (*fipsPrivateKey, error) {
	if k.precomputed != nil {
		return k.precomputed, nil
	}
	if k.pub.n == nil {
		return nil, errors.New("crypto/rsa: missing public modulus")
	}
	if k.d == nil {
		return nil, errors.New("crypto/rsa: missing private exponent")
	}
	N, e, d := k.pub.n.Bytes(), k.pub.e, k.d.Bytes()
	if len(k.primes) == 2 {
		if k.primes[0] == nil {
			return nil, errors.New("crypto/rsa: prime P is nil")
		}
		if k.primes[1] == nil {
			return nil, errors.New("crypto/rsa: prime Q is nil")
		}
		P, Q := k.primes[0].Bytes(), k.primes[1].Bytes()
		if k.dp != nil && k.dq != nil && k.qi != nil {
			return fallback.NewPrivateKeyWithPrecomputation(N, e, d, P, Q, k.dp.Bytes(), k.dq.Bytes(), k.qi.Bytes())
		}
		return fallback.NewPrivateKey(N, e, d, P, Q)
	}
	fk, err := fallback.NewPrivateKeyWithoutCRT(N, e, d)
	if err != nil || len(k.primes) < 2 {
		return fk, err
	}
	// Match the legacy precomputation checks without calculating CRT values
	// that the non-CRT Go representation does not use.
	one := big.NewInt(1)
	product := new(big.Int).Set(one)
	for _, p := range k.primes {
		if p == nil {
			return nil, errors.New("crypto/rsa: prime factor is nil")
		}
		if p.Cmp(one) <= 0 {
			return nil, errors.New("crypto/rsa: prime factor is <= 1")
		}
	}
	for _, p := range k.primes {
		if new(big.Int).GCD(nil, nil, product, p).Cmp(one) != 0 {
			return nil, errors.New("crypto/rsa: prime factors are not relatively prime")
		}
		product.Mul(product, p)
	}
	return fk, nil
}
