// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Command hashgen generates concrete native/fallback hash dispatchers.
// For each algorithm suffix X, the target package provides SupportsX,
// newBackendHashX, and initFallbackX.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type algorithm struct {
	Suffix      string
	Constant    string
	Constructor string
	First       bool
}

type config struct {
	Package        string
	Type           string
	FallbackImport string
	FallbackType   string
	Concrete       bool
	Algorithms     []algorithm
}

var sourceTemplate = template.Must(template.New("hash").Parse(`// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

package {{.Package}}

import (
	"hash"

	"github.com/microsoft/go/cryptobackend"
)

type hashAlgorithm uint8

const (
{{- range .Algorithms}}
	{{.Constant}}{{if .First}} hashAlgorithm = iota{{end}}
{{- end}}
)

// {{.Type}} dispatches hash operations to a native or fallback implementation.
// Its zero value selects {{(index .Algorithms 0).Constant}}.
type {{.Type}} struct {
	fips        fipsHash
	backend     *backendHash
	algorithm   hashAlgorithm
	initialized bool
}

func new{{.Type}}(algorithm hashAlgorithm) *{{.Type}} {
	return &{{.Type}}{algorithm: algorithm}
}

func (h *{{.Type}}) init() {
	if h.initialized {
		return
	}
	h.initialized = true
	switch h.algorithm {
{{- range .Algorithms}}
	case {{.Constant}}:
		if backend.Enabled && Supports{{.Suffix}}() {
			h.backend = newBackendHash{{.Suffix}}()
			return
		}
		h.fips = *initFallback{{.Suffix}}()
{{- end}}
	default:
		panic("cryptobackend: invalid hash algorithm")
	}
}

func (h *{{.Type}}) Write(p []byte) (int, error) {
	h.init()
	if h.backend != nil {
		return h.backend.Write(p)
	}
	return h.fips.Write(p)
}

func (h *{{.Type}}) Sum(p []byte) []byte {
	h.init()
	if h.backend != nil {
		return h.backend.Sum(p)
	}
	return h.fips.Sum(p)
}

func (h *{{.Type}}) Reset() {
	h.init()
	if h.backend != nil {
		h.backend.Reset()
		return
	}
	h.fips.Reset()
}

func (h *{{.Type}}) Size() int {
	h.init()
	if h.backend != nil {
		return h.backend.Size()
	}
	return h.fips.Size()
}

func (h *{{.Type}}) BlockSize() int {
	h.init()
	if h.backend != nil {
		return h.backend.BlockSize()
	}
	return h.fips.BlockSize()
}

func (h *{{.Type}}) MarshalBinary() ([]byte, error) {
	h.init()
	if h.backend != nil {
		return h.backend.MarshalBinary()
	}
	return h.fips.MarshalBinary()
}

func (h *{{.Type}}) AppendBinary(p []byte) ([]byte, error) {
	h.init()
	if h.backend != nil {
		return h.backend.AppendBinary(p)
	}
	return h.fips.AppendBinary(p)
}

func (h *{{.Type}}) UnmarshalBinary(data []byte) error {
	h.init()
	if h.backend != nil {
		return h.backend.UnmarshalBinary(data)
	}
	return h.fips.UnmarshalBinary(data)
}

func (h *{{.Type}}) Clone() (hash.Cloner, error) {
	r := *h
	r.init()
	if r.backend != nil {
		cloned, err := r.backend.Clone()
		if err != nil {
			return nil, err
		}
		r.backend = cloned.(*backendHash)
	}
	return &r, nil
}

func (h *{{.Type}}) unwrap() hash.Hash {
	h.init()
	if h.backend != nil {
		return h.backend
	}
	return &h.fips
}
`))

var msgostdTemplate = template.Must(template.New("msgostd").Parse(`// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build msgostd || cmd_go_bootstrap

package {{.Package}}

import (
	fallback {{printf "%q" .FallbackImport}}
	"hash"
)

type fipsHash = fallback.{{.FallbackType}}
{{range .Algorithms}}
func initFallback{{.Suffix}}() *fipsHash { return fallback.{{.Constructor}}() }
{{end}}
{{range .Algorithms}}
func {{.Constructor}}() *{{$.Type}} { return new{{$.Type}}({{.Constant}}) }
{{end}}
// Unwrap returns the selected hash implementation.
func Unwrap(h *{{.Type}}) hash.Hash { return h.unwrap() }
`))

var nomsgostdTemplate = template.Must(template.New("nomsgostd").Parse(`// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build !msgostd && !cmd_go_bootstrap

package {{.Package}}

import "hash"

type fipsHash struct{}

func (*fipsHash) Write([]byte) (int, error)      { panic("cryptobackend: not available") }
func (*fipsHash) Sum([]byte) []byte              { panic("cryptobackend: not available") }
func (*fipsHash) Reset()                         { panic("cryptobackend: not available") }
func (*fipsHash) Size() int                      { panic("cryptobackend: not available") }
func (*fipsHash) BlockSize() int                 { panic("cryptobackend: not available") }
func (*fipsHash) MarshalBinary() ([]byte, error) { panic("cryptobackend: not available") }
func (*fipsHash) AppendBinary([]byte) ([]byte, error) {
	panic("cryptobackend: not available")
}
func (*fipsHash) UnmarshalBinary([]byte) error { panic("cryptobackend: not available") }
func (*fipsHash) Clone() (hash.Cloner, error)  { panic("cryptobackend: not available") }
{{range .Algorithms}}
func initFallback{{.Suffix}}() *fipsHash { panic("cryptobackend: not available") }
{{end}}
{{range .Algorithms}}
{{if $.Concrete -}}
func {{.Constructor}}() *{{$.Type}} { return new{{$.Type}}({{.Constant}}) }
{{else -}}
func {{.Constructor}}() hash.Hash { return new{{$.Type}}({{.Constant}}) }
{{end -}}
{{end}}
`))

func main() {
	var algorithmList string
	var concrete bool
	flag.StringVar(&algorithmList, "algorithms", "", "comma-separated algorithm suffixes, with the default first")
	flag.BoolVar(&concrete, "concrete", false, "use concrete constructor results outside the standard library")
	flag.Parse()

	if err := run(algorithmList, concrete); err != nil {
		fmt.Fprintln(os.Stderr, "hashgen:", err)
		os.Exit(1)
	}
}

func run(algorithmList string, concrete bool) error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}
	packageName := filepath.Base(wd)
	if !token.IsIdentifier(packageName) {
		return fmt.Errorf("invalid package name %q", packageName)
	}

	var algorithms []algorithm
	seen := make(map[string]bool)
	constructors := make(map[string]bool)
	for _, value := range strings.Split(algorithmList, ",") {
		suffix := strings.TrimSpace(value)
		constant := "hashSHA" + suffix
		if suffix == "" || !token.IsIdentifier(constant) {
			return fmt.Errorf("invalid algorithm suffix %q", suffix)
		}
		constructor := "New" + suffix
		if len(algorithms) == 0 && !concrete {
			constructor = "New"
		}
		if seen[suffix] {
			return fmt.Errorf("duplicate algorithm suffix %q", suffix)
		}
		if constructors[constructor] {
			return fmt.Errorf("duplicate constructor %q", constructor)
		}
		seen[suffix] = true
		constructors[constructor] = true
		algorithms = append(algorithms, algorithm{Suffix: suffix, Constant: constant, Constructor: constructor, First: len(algorithms) == 0})
	}

	config := config{
		Package:        packageName,
		Type:           "Hash",
		FallbackImport: "crypto/internal/fips140/" + packageName,
		FallbackType:   "Digest",
		Concrete:       concrete,
		Algorithms:     algorithms,
	}
	outputs := []struct {
		path     string
		template *template.Template
	}{
		{"z" + packageName + ".go", sourceTemplate},
		{"z" + packageName + "_msgostd.go", msgostdTemplate},
		{"z" + packageName + "_nomsgostd.go", nomsgostdTemplate},
	}
	generated := make([][]byte, len(outputs))
	for i, output := range outputs {
		var source bytes.Buffer
		if err := output.template.Execute(&source, config); err != nil {
			return err
		}
		formatted, err := format.Source(source.Bytes())
		if err != nil {
			return fmt.Errorf("format generated source: %w", err)
		}
		generated[i] = formatted
	}
	for i, output := range outputs {
		if err := os.WriteFile(output.path, generated[i], 0o666); err != nil {
			return err
		}
	}
	return nil
}
