// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo && unix

package ossl

import (
	"runtime"
	"unsafe"
)

//go:cgo_import_dynamic _mkcgo_dlclose dlclose ""
//go:cgo_import_dynamic _mkcgo_dlerror dlerror ""
//go:cgo_import_dynamic _mkcgo_dlopen dlopen ""
//go:cgo_import_dynamic _mkcgo_dlsym dlsym ""

var _mkcgo_dlclose_trampoline_addr uintptr

func Dlclose(handle unsafe.Pointer) int32 {
	r0, _, _ := syscallN(_mkcgo_dlclose_trampoline_addr, uintptr(handle))
	return int32(r0)
}

var _mkcgo_dlerror_trampoline_addr uintptr

func Dlerror() *byte {
	r0, _, _ := syscallN(_mkcgo_dlerror_trampoline_addr)
	return (*byte)(unsafe.Pointer(r0))
}

var _mkcgo_dlopen_trampoline_addr uintptr

func Dlopen(path *byte, flags int32) unsafe.Pointer {
	r0, _, _ := syscallN(_mkcgo_dlopen_trampoline_addr, uintptr(unsafe.Pointer(path)), uintptr(flags))
	runtime.KeepAlive(path)
	return unsafe.Pointer(r0)
}

var _mkcgo_dlsym_trampoline_addr uintptr

func Dlsym(handle unsafe.Pointer, symbol *byte) unsafe.Pointer {
	r0, _, _ := syscallN(_mkcgo_dlsym_trampoline_addr, uintptr(handle), uintptr(unsafe.Pointer(symbol)))
	runtime.KeepAlive(symbol)
	return unsafe.Pointer(r0)
}
