// Code generated by mkcgo. DO NOT EDIT.

#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include "zossl.h"

#ifdef _WIN32
#include <windows.h>
#define dlsym GetProcAddress
#else
#include <dlfcn.h>
#endif

_BIGNUM_PTR (*_g_BN_bin2bn)(const unsigned char*, int, _BIGNUM_PTR);
int (*_g_BN_bn2binpad)(const _BIGNUM_PTR, unsigned char*, int);
int (*_g_BN_bn2lebinpad)(const _BIGNUM_PTR, unsigned char*, int);
void (*_g_BN_clear)(_BIGNUM_PTR);
void (*_g_BN_clear_free)(_BIGNUM_PTR);
void (*_g_BN_free)(_BIGNUM_PTR);
_BIGNUM_PTR (*_g_BN_lebin2bn)(const unsigned char*, int, _BIGNUM_PTR);
_BIGNUM_PTR (*_g_BN_new)(void);
int (*_g_BN_num_bits)(const _BIGNUM_PTR);
void (*_g_CRYPTO_free)(void*, const char*, int);
void* (*_g_CRYPTO_malloc)(size_t, const char*, int);
void (*_g_DSA_free)(_DSA_PTR);
int (*_g_DSA_generate_key)(_DSA_PTR);
void (*_g_DSA_get0_key)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_DSA_get0_pqg)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_DSA_PTR (*_g_DSA_new)(void);
int (*_g_DSA_set0_key)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_DSA_set0_pqg)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
void (*_g_EC_GROUP_free)(_EC_GROUP_PTR);
_EC_GROUP_PTR (*_g_EC_GROUP_new_by_curve_name)(int);
int (*_g_EC_KEY_check_key)(const _EC_KEY_PTR);
void (*_g_EC_KEY_free)(_EC_KEY_PTR);
const _EC_GROUP_PTR (*_g_EC_KEY_get0_group)(const _EC_KEY_PTR);
const _BIGNUM_PTR (*_g_EC_KEY_get0_private_key)(const _EC_KEY_PTR);
const _EC_POINT_PTR (*_g_EC_KEY_get0_public_key)(const _EC_KEY_PTR);
_EC_KEY_PTR (*_g_EC_KEY_new_by_curve_name)(int);
int (*_g_EC_KEY_set_private_key)(_EC_KEY_PTR, const _BIGNUM_PTR);
int (*_g_EC_KEY_set_public_key)(_EC_KEY_PTR, const _EC_POINT_PTR);
int (*_g_EC_KEY_set_public_key_affine_coordinates)(_EC_KEY_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
void (*_g_EC_POINT_free)(_EC_POINT_PTR);
int (*_g_EC_POINT_get_affine_coordinates_GFp)(const _EC_GROUP_PTR, const _EC_POINT_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BN_CTX_PTR);
int (*_g_EC_POINT_mul)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _EC_POINT_PTR, const _BIGNUM_PTR, _BN_CTX_PTR);
_EC_POINT_PTR (*_g_EC_POINT_new)(const _EC_GROUP_PTR);
int (*_g_EC_POINT_oct2point)(const _EC_GROUP_PTR, _EC_POINT_PTR, const unsigned char*, size_t, _BN_CTX_PTR);
size_t (*_g_EC_POINT_point2oct)(const _EC_GROUP_PTR, const _EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, _BN_CTX_PTR);
int (*_g_EC_POINT_set_affine_coordinates)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _BIGNUM_PTR, _BN_CTX_PTR);
void (*_g_ERR_clear_error)(void);
void (*_g_ERR_error_string_n)(unsigned long, char*, size_t);
unsigned long (*_g_ERR_get_error_all)(const char**, int*, const char**, const char**, int*);
unsigned long (*_g_ERR_get_error_line)(const char**, int*);
int (*_g_EVP_CIPHER_CTX_ctrl)(_EVP_CIPHER_CTX_PTR, int, int, void*);
void (*_g_EVP_CIPHER_CTX_free)(_EVP_CIPHER_CTX_PTR);
_EVP_CIPHER_CTX_PTR (*_g_EVP_CIPHER_CTX_new)(void);
int (*_g_EVP_CIPHER_CTX_set_key_length)(_EVP_CIPHER_CTX_PTR, int);
int (*_g_EVP_CIPHER_CTX_set_padding)(_EVP_CIPHER_CTX_PTR, int);
_EVP_CIPHER_PTR (*_g_EVP_CIPHER_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
const char* (*_g_EVP_CIPHER_get0_name)(const _EVP_CIPHER_PTR);
int (*_g_EVP_CIPHER_get_block_size)(const _EVP_CIPHER_PTR);
int (*_g_EVP_CipherInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, int);
int (*_g_EVP_CipherUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_DecryptFinal_ex)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_DecryptInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_DecryptUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_Digest)(const void*, size_t, unsigned char*, unsigned int*, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_EVP_DigestFinal_ex)(_EVP_MD_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_EVP_DigestInit)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR);
int (*_g_EVP_DigestInit_ex)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_EVP_DigestSign)(_EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_DigestSignFinal)(_EVP_MD_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_DigestSignInit)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_DigestUpdate)(_EVP_MD_CTX_PTR, const void*, size_t);
int (*_g_EVP_DigestVerify)(_EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyFinal)(_EVP_MD_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyInit)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_EncryptFinal_ex)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_EncryptInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_EncryptUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
void (*_g_EVP_KDF_CTX_free)(_EVP_KDF_CTX_PTR);
size_t (*_g_EVP_KDF_CTX_get_kdf_size)(_EVP_KDF_CTX_PTR);
_EVP_KDF_CTX_PTR (*_g_EVP_KDF_CTX_new)(_EVP_KDF_PTR);
int (*_g_EVP_KDF_CTX_set_params)(_EVP_KDF_CTX_PTR, const _OSSL_PARAM_PTR);
int (*_g_EVP_KDF_derive)(_EVP_KDF_CTX_PTR, unsigned char*, size_t, const _OSSL_PARAM_PTR);
_EVP_KDF_PTR (*_g_EVP_KDF_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_KDF_free)(_EVP_KDF_PTR);
_EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_dup)(const _EVP_MAC_CTX_PTR);
void (*_g_EVP_MAC_CTX_free)(_EVP_MAC_CTX_PTR);
_EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_new)(_EVP_MAC_PTR);
int (*_g_EVP_MAC_CTX_set_params)(_EVP_MAC_CTX_PTR, const _OSSL_PARAM_PTR);
_EVP_MAC_PTR (*_g_EVP_MAC_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
int (*_g_EVP_MAC_final)(_EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t);
int (*_g_EVP_MAC_init)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t, const _OSSL_PARAM_PTR);
int (*_g_EVP_MAC_update)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_MD_CTX_copy)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR);
int (*_g_EVP_MD_CTX_copy_ex)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR);
void (*_g_EVP_MD_CTX_free)(_EVP_MD_CTX_PTR);
int (*_g_EVP_MD_CTX_get_params)(_EVP_MD_CTX_PTR, _OSSL_PARAM_PTR);
const _OSSL_PARAM_PTR (*_g_EVP_MD_CTX_gettable_params)(_EVP_MD_CTX_PTR);
_EVP_MD_CTX_PTR (*_g_EVP_MD_CTX_new)(void);
int (*_g_EVP_MD_CTX_set_params)(_EVP_MD_CTX_PTR, const _OSSL_PARAM_PTR);
const _OSSL_PARAM_PTR (*_g_EVP_MD_CTX_settable_params)(_EVP_MD_CTX_PTR);
_EVP_MD_PTR (*_g_EVP_MD_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_MD_free)(_EVP_MD_PTR);
const char* (*_g_EVP_MD_get0_name)(const _EVP_MD_PTR);
const _OSSL_PROVIDER_PTR (*_g_EVP_MD_get0_provider)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_block_size)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_size)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_type)(const _EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_add1_hkdf_info)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_ctrl)(_EVP_PKEY_CTX_PTR, int, int, int, int, void*);
void (*_g_EVP_PKEY_CTX_free)(_EVP_PKEY_CTX_PTR);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new)(_EVP_PKEY_PTR, _ENGINE_PTR);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_from_pkey)(_OSSL_LIB_CTX_PTR, _EVP_PKEY_PTR, const char*);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_id)(int, _ENGINE_PTR);
int (*_g_EVP_PKEY_CTX_set0_rsa_oaep_label)(_EVP_PKEY_CTX_PTR, void*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_key)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_salt)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set_hkdf_md)(_EVP_PKEY_CTX_PTR, const _EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_set_hkdf_mode)(_EVP_PKEY_CTX_PTR, int);
_EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen)(_OSSL_LIB_CTX_PTR, const char*, const char*, ...);
int (*_g_EVP_PKEY_assign)(_EVP_PKEY_PTR, int, void*);
int (*_g_EVP_PKEY_decrypt)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_decrypt_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_derive_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive_set_peer)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_encrypt)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_encrypt_init)(_EVP_PKEY_CTX_PTR);
void (*_g_EVP_PKEY_free)(_EVP_PKEY_PTR);
int (*_g_EVP_PKEY_fromdata)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, int, _OSSL_PARAM_PTR);
int (*_g_EVP_PKEY_fromdata_init)(_EVP_PKEY_CTX_PTR);
_DSA_PTR (*_g_EVP_PKEY_get0_DSA)(_EVP_PKEY_PTR);
_EC_KEY_PTR (*_g_EVP_PKEY_get0_EC_KEY)(_EVP_PKEY_PTR);
_RSA_PTR (*_g_EVP_PKEY_get1_RSA)(_EVP_PKEY_PTR);
size_t (*_g_EVP_PKEY_get1_encoded_public_key)(_EVP_PKEY_PTR, unsigned char**);
int (*_g_EVP_PKEY_get_bits)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_get_bn_param)(const _EVP_PKEY_PTR, const char*, _BIGNUM_PTR*);
int (*_g_EVP_PKEY_get_raw_private_key)(const _EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_raw_public_key)(const _EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_size)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_keygen)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_keygen_init)(_EVP_PKEY_CTX_PTR);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new)(void);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_private_key)(int, _ENGINE_PTR, const unsigned char*, size_t);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_public_key)(int, _ENGINE_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_paramgen)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_paramgen_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_private_check)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_public_check_quick)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_set1_EC_KEY)(_EVP_PKEY_PTR, _EC_KEY_PTR);
int (*_g_EVP_PKEY_set1_encoded_public_key)(_EVP_PKEY_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_up_ref)(_EVP_PKEY_PTR);
int (*_g_EVP_PKEY_verify)(_EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_PKEY_verify_init)(_EVP_PKEY_CTX_PTR);
_EVP_SIGNATURE_PTR (*_g_EVP_SIGNATURE_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_SIGNATURE_free)(_EVP_SIGNATURE_PTR);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_gcm)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_gcm)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_gcm)(void);
int (*_g_EVP_default_properties_enable_fips)(_OSSL_LIB_CTX_PTR, int);
int (*_g_EVP_default_properties_is_fips_enabled)(_OSSL_LIB_CTX_PTR);
const _EVP_CIPHER_PTR (*_g_EVP_des_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ede3_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ede3_ecb)(void);
const _EVP_MD_PTR (*_g_EVP_md4)(void);
const _EVP_MD_PTR (*_g_EVP_md5)(void);
const _EVP_MD_PTR (*_g_EVP_md5_sha1)(void);
const _EVP_CIPHER_PTR (*_g_EVP_rc4)(void);
const _EVP_MD_PTR (*_g_EVP_ripemd160)(void);
const _EVP_MD_PTR (*_g_EVP_sha1)(void);
const _EVP_MD_PTR (*_g_EVP_sha224)(void);
const _EVP_MD_PTR (*_g_EVP_sha256)(void);
const _EVP_MD_PTR (*_g_EVP_sha384)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_224)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_256)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_384)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_512)(void);
const _EVP_MD_PTR (*_g_EVP_sha512)(void);
const _EVP_MD_PTR (*_g_EVP_sha512_224)(void);
const _EVP_MD_PTR (*_g_EVP_sha512_256)(void);
int (*_g_FIPS_mode)(void);
int (*_g_FIPS_mode_set)(int);
int (*_g_HMAC_CTX_copy)(_HMAC_CTX_PTR, _HMAC_CTX_PTR);
void (*_g_HMAC_CTX_free)(_HMAC_CTX_PTR);
_HMAC_CTX_PTR (*_g_HMAC_CTX_new)(void);
int (*_g_HMAC_Final)(_HMAC_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_HMAC_Init_ex)(_HMAC_CTX_PTR, const void*, int, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_HMAC_Update)(_HMAC_CTX_PTR, const unsigned char*, size_t);
const char* (*_g_OBJ_nid2sn)(int);
void (*_g_OPENSSL_init)(void);
int (*_g_OPENSSL_init_crypto)(uint64_t, const _OPENSSL_INIT_SETTINGS_PTR);
unsigned int (*_g_OPENSSL_version_major)(void);
unsigned int (*_g_OPENSSL_version_minor)(void);
unsigned int (*_g_OPENSSL_version_patch)(void);
void (*_g_OSSL_PARAM_BLD_free)(_OSSL_PARAM_BLD_PTR);
_OSSL_PARAM_BLD_PTR (*_g_OSSL_PARAM_BLD_new)(void);
int (*_g_OSSL_PARAM_BLD_push_BN)(_OSSL_PARAM_BLD_PTR, const char*, const _BIGNUM_PTR);
int (*_g_OSSL_PARAM_BLD_push_int32)(_OSSL_PARAM_BLD_PTR, const char*, int32_t);
int (*_g_OSSL_PARAM_BLD_push_octet_string)(_OSSL_PARAM_BLD_PTR, const char*, const void*, size_t);
int (*_g_OSSL_PARAM_BLD_push_utf8_string)(_OSSL_PARAM_BLD_PTR, const char*, const char*, size_t);
_OSSL_PARAM_PTR (*_g_OSSL_PARAM_BLD_to_param)(_OSSL_PARAM_BLD_PTR);
void (*_g_OSSL_PARAM_free)(_OSSL_PARAM_PTR);
const _OSSL_PARAM_PTR (*_g_OSSL_PARAM_locate_const)(const _OSSL_PARAM_PTR, const char*);
int (*_g_OSSL_PROVIDER_available)(_OSSL_LIB_CTX_PTR, const char*);
const char* (*_g_OSSL_PROVIDER_get0_name)(const _OSSL_PROVIDER_PTR);
_OSSL_PROVIDER_PTR (*_g_OSSL_PROVIDER_try_load)(_OSSL_LIB_CTX_PTR, const char*, int);
const char* (*_g_OpenSSL_version)(int);
unsigned long (*_g_OpenSSL_version_num)(void);
int (*_g_PKCS5_PBKDF2_HMAC)(const char*, int, const unsigned char*, int, int, const _EVP_MD_PTR, int, unsigned char*);
int (*_g_RAND_bytes)(unsigned char*, int);
void (*_g_RSA_free)(_RSA_PTR);
void (*_g_RSA_get0_crt_params)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_RSA_get0_factors)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_RSA_get0_key)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_RSA_PTR (*_g_RSA_new)(void);
int (*_g_RSA_set0_crt_params)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_RSA_set0_factors)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_RSA_set0_key)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);

#define __mkcgo__dlsym_nocheck(varname, funcname) _g_##varname = (typeof(_g_##varname))dlsym(handle, #funcname);

#define __mkcgo__dlsym(name) __mkcgo__dlsym2(name, name)

#define __mkcgo__dlsym2(varname, funcname) \
	__mkcgo__dlsym_nocheck(varname, funcname) \
	if (_g_##varname == NULL) { \
		fprintf(stderr, "Cannot get required symbol " #funcname "\n"); \
		abort(); \
	}

void __mkcgo_load_(void* handle) {
	__mkcgo__dlsym(BN_bin2bn)
	__mkcgo__dlsym(BN_bn2binpad)
	__mkcgo__dlsym(BN_bn2lebinpad)
	__mkcgo__dlsym(BN_clear)
	__mkcgo__dlsym(BN_clear_free)
	__mkcgo__dlsym(BN_free)
	__mkcgo__dlsym(BN_lebin2bn)
	__mkcgo__dlsym(BN_new)
	__mkcgo__dlsym(BN_num_bits)
	__mkcgo__dlsym(CRYPTO_free)
	__mkcgo__dlsym(CRYPTO_malloc)
	__mkcgo__dlsym(EC_GROUP_free)
	__mkcgo__dlsym(EC_GROUP_new_by_curve_name)
	__mkcgo__dlsym(EC_POINT_free)
	__mkcgo__dlsym(EC_POINT_mul)
	__mkcgo__dlsym(EC_POINT_new)
	__mkcgo__dlsym(EC_POINT_oct2point)
	__mkcgo__dlsym(EC_POINT_point2oct)
	__mkcgo__dlsym(ERR_clear_error)
	__mkcgo__dlsym(ERR_error_string_n)
	__mkcgo__dlsym(EVP_CIPHER_CTX_ctrl)
	__mkcgo__dlsym(EVP_CIPHER_CTX_free)
	__mkcgo__dlsym(EVP_CIPHER_CTX_new)
	__mkcgo__dlsym(EVP_CIPHER_CTX_set_key_length)
	__mkcgo__dlsym(EVP_CIPHER_CTX_set_padding)
	__mkcgo__dlsym(EVP_CipherInit_ex)
	__mkcgo__dlsym(EVP_CipherUpdate)
	__mkcgo__dlsym(EVP_DecryptFinal_ex)
	__mkcgo__dlsym(EVP_DecryptInit_ex)
	__mkcgo__dlsym(EVP_DecryptUpdate)
	__mkcgo__dlsym(EVP_Digest)
	__mkcgo__dlsym(EVP_DigestFinal_ex)
	__mkcgo__dlsym(EVP_DigestInit)
	__mkcgo__dlsym(EVP_DigestInit_ex)
	__mkcgo__dlsym(EVP_DigestSignFinal)
	__mkcgo__dlsym(EVP_DigestSignInit)
	__mkcgo__dlsym(EVP_DigestUpdate)
	__mkcgo__dlsym(EVP_DigestVerifyFinal)
	__mkcgo__dlsym(EVP_DigestVerifyInit)
	__mkcgo__dlsym(EVP_EncryptFinal_ex)
	__mkcgo__dlsym(EVP_EncryptInit_ex)
	__mkcgo__dlsym(EVP_EncryptUpdate)
	__mkcgo__dlsym(EVP_MD_CTX_copy)
	__mkcgo__dlsym(EVP_MD_CTX_copy_ex)
	__mkcgo__dlsym(EVP_MD_CTX_free)
	__mkcgo__dlsym(EVP_MD_CTX_new)
	__mkcgo__dlsym(EVP_PKEY_CTX_ctrl)
	__mkcgo__dlsym(EVP_PKEY_CTX_free)
	__mkcgo__dlsym(EVP_PKEY_CTX_new)
	__mkcgo__dlsym(EVP_PKEY_CTX_new_id)
	__mkcgo__dlsym(EVP_PKEY_decrypt)
	__mkcgo__dlsym(EVP_PKEY_decrypt_init)
	__mkcgo__dlsym(EVP_PKEY_derive)
	__mkcgo__dlsym(EVP_PKEY_derive_init)
	__mkcgo__dlsym(EVP_PKEY_derive_set_peer)
	__mkcgo__dlsym(EVP_PKEY_encrypt)
	__mkcgo__dlsym(EVP_PKEY_encrypt_init)
	__mkcgo__dlsym(EVP_PKEY_free)
	__mkcgo__dlsym(EVP_PKEY_keygen)
	__mkcgo__dlsym(EVP_PKEY_keygen_init)
	__mkcgo__dlsym(EVP_PKEY_new)
	__mkcgo__dlsym(EVP_PKEY_paramgen)
	__mkcgo__dlsym(EVP_PKEY_paramgen_init)
	__mkcgo__dlsym(EVP_PKEY_sign)
	__mkcgo__dlsym(EVP_PKEY_sign_init)
	__mkcgo__dlsym(EVP_PKEY_verify)
	__mkcgo__dlsym(EVP_PKEY_verify_init)
	__mkcgo__dlsym(EVP_aes_128_cbc)
	__mkcgo__dlsym(EVP_aes_128_ctr)
	__mkcgo__dlsym(EVP_aes_128_ecb)
	__mkcgo__dlsym(EVP_aes_128_gcm)
	__mkcgo__dlsym(EVP_aes_192_cbc)
	__mkcgo__dlsym(EVP_aes_192_ctr)
	__mkcgo__dlsym(EVP_aes_192_ecb)
	__mkcgo__dlsym(EVP_aes_192_gcm)
	__mkcgo__dlsym(EVP_aes_256_cbc)
	__mkcgo__dlsym(EVP_aes_256_ctr)
	__mkcgo__dlsym(EVP_aes_256_ecb)
	__mkcgo__dlsym(EVP_aes_256_gcm)
	__mkcgo__dlsym(EVP_des_cbc)
	__mkcgo__dlsym(EVP_des_ecb)
	__mkcgo__dlsym(EVP_des_ede3_cbc)
	__mkcgo__dlsym(EVP_des_ede3_ecb)
	__mkcgo__dlsym(EVP_md4)
	__mkcgo__dlsym(EVP_md5)
	__mkcgo__dlsym(EVP_md5_sha1)
	__mkcgo__dlsym(EVP_rc4)
	__mkcgo__dlsym(EVP_ripemd160)
	__mkcgo__dlsym(EVP_sha1)
	__mkcgo__dlsym(EVP_sha224)
	__mkcgo__dlsym(EVP_sha256)
	__mkcgo__dlsym(EVP_sha384)
	__mkcgo__dlsym(EVP_sha512)
	__mkcgo__dlsym(OBJ_nid2sn)
	__mkcgo__dlsym(OPENSSL_init)
	__mkcgo__dlsym(OPENSSL_init_crypto)
	__mkcgo__dlsym(OpenSSL_version)
	__mkcgo__dlsym(PKCS5_PBKDF2_HMAC)
	__mkcgo__dlsym(RAND_bytes)
}

void __mkcgo_unload_() {
	_g_BN_bin2bn = NULL;
	_g_BN_bn2binpad = NULL;
	_g_BN_bn2lebinpad = NULL;
	_g_BN_clear = NULL;
	_g_BN_clear_free = NULL;
	_g_BN_free = NULL;
	_g_BN_lebin2bn = NULL;
	_g_BN_new = NULL;
	_g_BN_num_bits = NULL;
	_g_CRYPTO_free = NULL;
	_g_CRYPTO_malloc = NULL;
	_g_EC_GROUP_free = NULL;
	_g_EC_GROUP_new_by_curve_name = NULL;
	_g_EC_POINT_free = NULL;
	_g_EC_POINT_mul = NULL;
	_g_EC_POINT_new = NULL;
	_g_EC_POINT_oct2point = NULL;
	_g_EC_POINT_point2oct = NULL;
	_g_ERR_clear_error = NULL;
	_g_ERR_error_string_n = NULL;
	_g_EVP_CIPHER_CTX_ctrl = NULL;
	_g_EVP_CIPHER_CTX_free = NULL;
	_g_EVP_CIPHER_CTX_new = NULL;
	_g_EVP_CIPHER_CTX_set_key_length = NULL;
	_g_EVP_CIPHER_CTX_set_padding = NULL;
	_g_EVP_CipherInit_ex = NULL;
	_g_EVP_CipherUpdate = NULL;
	_g_EVP_DecryptFinal_ex = NULL;
	_g_EVP_DecryptInit_ex = NULL;
	_g_EVP_DecryptUpdate = NULL;
	_g_EVP_Digest = NULL;
	_g_EVP_DigestFinal_ex = NULL;
	_g_EVP_DigestInit = NULL;
	_g_EVP_DigestInit_ex = NULL;
	_g_EVP_DigestSignFinal = NULL;
	_g_EVP_DigestSignInit = NULL;
	_g_EVP_DigestUpdate = NULL;
	_g_EVP_DigestVerifyFinal = NULL;
	_g_EVP_DigestVerifyInit = NULL;
	_g_EVP_EncryptFinal_ex = NULL;
	_g_EVP_EncryptInit_ex = NULL;
	_g_EVP_EncryptUpdate = NULL;
	_g_EVP_MD_CTX_copy = NULL;
	_g_EVP_MD_CTX_copy_ex = NULL;
	_g_EVP_MD_CTX_free = NULL;
	_g_EVP_MD_CTX_new = NULL;
	_g_EVP_PKEY_CTX_ctrl = NULL;
	_g_EVP_PKEY_CTX_free = NULL;
	_g_EVP_PKEY_CTX_new = NULL;
	_g_EVP_PKEY_CTX_new_id = NULL;
	_g_EVP_PKEY_decrypt = NULL;
	_g_EVP_PKEY_decrypt_init = NULL;
	_g_EVP_PKEY_derive = NULL;
	_g_EVP_PKEY_derive_init = NULL;
	_g_EVP_PKEY_derive_set_peer = NULL;
	_g_EVP_PKEY_encrypt = NULL;
	_g_EVP_PKEY_encrypt_init = NULL;
	_g_EVP_PKEY_free = NULL;
	_g_EVP_PKEY_keygen = NULL;
	_g_EVP_PKEY_keygen_init = NULL;
	_g_EVP_PKEY_new = NULL;
	_g_EVP_PKEY_paramgen = NULL;
	_g_EVP_PKEY_paramgen_init = NULL;
	_g_EVP_PKEY_sign = NULL;
	_g_EVP_PKEY_sign_init = NULL;
	_g_EVP_PKEY_verify = NULL;
	_g_EVP_PKEY_verify_init = NULL;
	_g_EVP_aes_128_cbc = NULL;
	_g_EVP_aes_128_ctr = NULL;
	_g_EVP_aes_128_ecb = NULL;
	_g_EVP_aes_128_gcm = NULL;
	_g_EVP_aes_192_cbc = NULL;
	_g_EVP_aes_192_ctr = NULL;
	_g_EVP_aes_192_ecb = NULL;
	_g_EVP_aes_192_gcm = NULL;
	_g_EVP_aes_256_cbc = NULL;
	_g_EVP_aes_256_ctr = NULL;
	_g_EVP_aes_256_ecb = NULL;
	_g_EVP_aes_256_gcm = NULL;
	_g_EVP_des_cbc = NULL;
	_g_EVP_des_ecb = NULL;
	_g_EVP_des_ede3_cbc = NULL;
	_g_EVP_des_ede3_ecb = NULL;
	_g_EVP_md4 = NULL;
	_g_EVP_md5 = NULL;
	_g_EVP_md5_sha1 = NULL;
	_g_EVP_rc4 = NULL;
	_g_EVP_ripemd160 = NULL;
	_g_EVP_sha1 = NULL;
	_g_EVP_sha224 = NULL;
	_g_EVP_sha256 = NULL;
	_g_EVP_sha384 = NULL;
	_g_EVP_sha512 = NULL;
	_g_OBJ_nid2sn = NULL;
	_g_OPENSSL_init = NULL;
	_g_OPENSSL_init_crypto = NULL;
	_g_OpenSSL_version = NULL;
	_g_PKCS5_PBKDF2_HMAC = NULL;
	_g_RAND_bytes = NULL;
}

void __mkcgo_load_111(void* handle) {
	__mkcgo__dlsym(EVP_DigestSign)
	__mkcgo__dlsym(EVP_DigestVerify)
	__mkcgo__dlsym(EVP_PKEY_get_raw_private_key)
	__mkcgo__dlsym(EVP_PKEY_get_raw_public_key)
	__mkcgo__dlsym(EVP_PKEY_new_raw_private_key)
	__mkcgo__dlsym(EVP_PKEY_new_raw_public_key)
	__mkcgo__dlsym(EVP_sha3_224)
	__mkcgo__dlsym(EVP_sha3_256)
	__mkcgo__dlsym(EVP_sha3_384)
	__mkcgo__dlsym(EVP_sha3_512)
	__mkcgo__dlsym(EVP_sha512_224)
	__mkcgo__dlsym(EVP_sha512_256)
}

void __mkcgo_unload_111() {
	_g_EVP_DigestSign = NULL;
	_g_EVP_DigestVerify = NULL;
	_g_EVP_PKEY_get_raw_private_key = NULL;
	_g_EVP_PKEY_get_raw_public_key = NULL;
	_g_EVP_PKEY_new_raw_private_key = NULL;
	_g_EVP_PKEY_new_raw_public_key = NULL;
	_g_EVP_sha3_224 = NULL;
	_g_EVP_sha3_256 = NULL;
	_g_EVP_sha3_384 = NULL;
	_g_EVP_sha3_512 = NULL;
	_g_EVP_sha512_224 = NULL;
	_g_EVP_sha512_256 = NULL;
}

void __mkcgo_load_3(void* handle) {
	__mkcgo__dlsym(EC_POINT_set_affine_coordinates)
	__mkcgo__dlsym(ERR_get_error_all)
	__mkcgo__dlsym(EVP_CIPHER_fetch)
	__mkcgo__dlsym(EVP_CIPHER_get0_name)
	__mkcgo__dlsym(EVP_CIPHER_get_block_size)
	__mkcgo__dlsym(EVP_KDF_CTX_free)
	__mkcgo__dlsym(EVP_KDF_CTX_get_kdf_size)
	__mkcgo__dlsym(EVP_KDF_CTX_new)
	__mkcgo__dlsym(EVP_KDF_CTX_set_params)
	__mkcgo__dlsym(EVP_KDF_derive)
	__mkcgo__dlsym(EVP_KDF_fetch)
	__mkcgo__dlsym(EVP_KDF_free)
	__mkcgo__dlsym(EVP_MAC_CTX_dup)
	__mkcgo__dlsym(EVP_MAC_CTX_free)
	__mkcgo__dlsym(EVP_MAC_CTX_new)
	__mkcgo__dlsym(EVP_MAC_CTX_set_params)
	__mkcgo__dlsym(EVP_MAC_fetch)
	__mkcgo__dlsym(EVP_MAC_final)
	__mkcgo__dlsym(EVP_MAC_init)
	__mkcgo__dlsym(EVP_MAC_update)
	__mkcgo__dlsym(EVP_MD_CTX_get_params)
	__mkcgo__dlsym(EVP_MD_CTX_gettable_params)
	__mkcgo__dlsym(EVP_MD_CTX_set_params)
	__mkcgo__dlsym(EVP_MD_CTX_settable_params)
	__mkcgo__dlsym(EVP_MD_fetch)
	__mkcgo__dlsym(EVP_MD_free)
	__mkcgo__dlsym(EVP_MD_get0_name)
	__mkcgo__dlsym(EVP_MD_get0_provider)
	__mkcgo__dlsym(EVP_MD_get_block_size)
	__mkcgo__dlsym(EVP_MD_get_size)
	__mkcgo__dlsym(EVP_MD_get_type)
	__mkcgo__dlsym(EVP_PKEY_CTX_add1_hkdf_info)
	__mkcgo__dlsym(EVP_PKEY_CTX_new_from_pkey)
	__mkcgo__dlsym(EVP_PKEY_CTX_set0_rsa_oaep_label)
	__mkcgo__dlsym(EVP_PKEY_CTX_set1_hkdf_key)
	__mkcgo__dlsym(EVP_PKEY_CTX_set1_hkdf_salt)
	__mkcgo__dlsym(EVP_PKEY_CTX_set_hkdf_md)
	__mkcgo__dlsym(EVP_PKEY_CTX_set_hkdf_mode)
	__mkcgo__dlsym(EVP_PKEY_Q_keygen)
	__mkcgo__dlsym(EVP_PKEY_fromdata)
	__mkcgo__dlsym(EVP_PKEY_fromdata_init)
	__mkcgo__dlsym(EVP_PKEY_get1_encoded_public_key)
	__mkcgo__dlsym(EVP_PKEY_get_bits)
	__mkcgo__dlsym(EVP_PKEY_get_bn_param)
	__mkcgo__dlsym(EVP_PKEY_get_size)
	__mkcgo__dlsym(EVP_PKEY_private_check)
	__mkcgo__dlsym(EVP_PKEY_public_check_quick)
	__mkcgo__dlsym(EVP_PKEY_set1_encoded_public_key)
	__mkcgo__dlsym(EVP_PKEY_up_ref)
	__mkcgo__dlsym(EVP_SIGNATURE_fetch)
	__mkcgo__dlsym(EVP_SIGNATURE_free)
	__mkcgo__dlsym(EVP_default_properties_enable_fips)
	__mkcgo__dlsym(EVP_default_properties_is_fips_enabled)
	__mkcgo__dlsym(OSSL_PARAM_BLD_free)
	__mkcgo__dlsym(OSSL_PARAM_BLD_new)
	__mkcgo__dlsym(OSSL_PARAM_BLD_push_BN)
	__mkcgo__dlsym(OSSL_PARAM_BLD_push_int32)
	__mkcgo__dlsym(OSSL_PARAM_BLD_push_octet_string)
	__mkcgo__dlsym(OSSL_PARAM_BLD_push_utf8_string)
	__mkcgo__dlsym(OSSL_PARAM_BLD_to_param)
	__mkcgo__dlsym(OSSL_PARAM_free)
	__mkcgo__dlsym(OSSL_PARAM_locate_const)
	__mkcgo__dlsym(OSSL_PROVIDER_available)
	__mkcgo__dlsym(OSSL_PROVIDER_get0_name)
	__mkcgo__dlsym(OSSL_PROVIDER_try_load)
}

void __mkcgo_unload_3() {
	_g_EC_POINT_set_affine_coordinates = NULL;
	_g_ERR_get_error_all = NULL;
	_g_EVP_CIPHER_fetch = NULL;
	_g_EVP_CIPHER_get0_name = NULL;
	_g_EVP_CIPHER_get_block_size = NULL;
	_g_EVP_KDF_CTX_free = NULL;
	_g_EVP_KDF_CTX_get_kdf_size = NULL;
	_g_EVP_KDF_CTX_new = NULL;
	_g_EVP_KDF_CTX_set_params = NULL;
	_g_EVP_KDF_derive = NULL;
	_g_EVP_KDF_fetch = NULL;
	_g_EVP_KDF_free = NULL;
	_g_EVP_MAC_CTX_dup = NULL;
	_g_EVP_MAC_CTX_free = NULL;
	_g_EVP_MAC_CTX_new = NULL;
	_g_EVP_MAC_CTX_set_params = NULL;
	_g_EVP_MAC_fetch = NULL;
	_g_EVP_MAC_final = NULL;
	_g_EVP_MAC_init = NULL;
	_g_EVP_MAC_update = NULL;
	_g_EVP_MD_CTX_get_params = NULL;
	_g_EVP_MD_CTX_gettable_params = NULL;
	_g_EVP_MD_CTX_set_params = NULL;
	_g_EVP_MD_CTX_settable_params = NULL;
	_g_EVP_MD_fetch = NULL;
	_g_EVP_MD_free = NULL;
	_g_EVP_MD_get0_name = NULL;
	_g_EVP_MD_get0_provider = NULL;
	_g_EVP_MD_get_block_size = NULL;
	_g_EVP_MD_get_size = NULL;
	_g_EVP_MD_get_type = NULL;
	_g_EVP_PKEY_CTX_add1_hkdf_info = NULL;
	_g_EVP_PKEY_CTX_new_from_pkey = NULL;
	_g_EVP_PKEY_CTX_set0_rsa_oaep_label = NULL;
	_g_EVP_PKEY_CTX_set1_hkdf_key = NULL;
	_g_EVP_PKEY_CTX_set1_hkdf_salt = NULL;
	_g_EVP_PKEY_CTX_set_hkdf_md = NULL;
	_g_EVP_PKEY_CTX_set_hkdf_mode = NULL;
	_g_EVP_PKEY_Q_keygen = NULL;
	_g_EVP_PKEY_fromdata = NULL;
	_g_EVP_PKEY_fromdata_init = NULL;
	_g_EVP_PKEY_get1_encoded_public_key = NULL;
	_g_EVP_PKEY_get_bits = NULL;
	_g_EVP_PKEY_get_bn_param = NULL;
	_g_EVP_PKEY_get_size = NULL;
	_g_EVP_PKEY_private_check = NULL;
	_g_EVP_PKEY_public_check_quick = NULL;
	_g_EVP_PKEY_set1_encoded_public_key = NULL;
	_g_EVP_PKEY_up_ref = NULL;
	_g_EVP_SIGNATURE_fetch = NULL;
	_g_EVP_SIGNATURE_free = NULL;
	_g_EVP_default_properties_enable_fips = NULL;
	_g_EVP_default_properties_is_fips_enabled = NULL;
	_g_OSSL_PARAM_BLD_free = NULL;
	_g_OSSL_PARAM_BLD_new = NULL;
	_g_OSSL_PARAM_BLD_push_BN = NULL;
	_g_OSSL_PARAM_BLD_push_int32 = NULL;
	_g_OSSL_PARAM_BLD_push_octet_string = NULL;
	_g_OSSL_PARAM_BLD_push_utf8_string = NULL;
	_g_OSSL_PARAM_BLD_to_param = NULL;
	_g_OSSL_PARAM_free = NULL;
	_g_OSSL_PARAM_locate_const = NULL;
	_g_OSSL_PROVIDER_available = NULL;
	_g_OSSL_PROVIDER_get0_name = NULL;
	_g_OSSL_PROVIDER_try_load = NULL;
}

void __mkcgo_load_init_1(void* handle) {
	__mkcgo__dlsym(FIPS_mode)
	__mkcgo__dlsym(FIPS_mode_set)
}

void __mkcgo_unload_init_1() {
	_g_FIPS_mode = NULL;
	_g_FIPS_mode_set = NULL;
}

void __mkcgo_load_init_3(void* handle) {
	__mkcgo__dlsym(ERR_clear_error)
	__mkcgo__dlsym(EVP_MD_fetch)
	__mkcgo__dlsym(EVP_MD_free)
	__mkcgo__dlsym(EVP_MD_get0_provider)
	__mkcgo__dlsym(EVP_default_properties_is_fips_enabled)
}

void __mkcgo_unload_init_3() {
	_g_ERR_clear_error = NULL;
	_g_EVP_MD_fetch = NULL;
	_g_EVP_MD_free = NULL;
	_g_EVP_MD_get0_provider = NULL;
	_g_EVP_default_properties_is_fips_enabled = NULL;
}

void __mkcgo_load_legacy_1(void* handle) {
	__mkcgo__dlsym(DSA_free)
	__mkcgo__dlsym(DSA_generate_key)
	__mkcgo__dlsym(DSA_get0_key)
	__mkcgo__dlsym(DSA_get0_pqg)
	__mkcgo__dlsym(DSA_new)
	__mkcgo__dlsym(DSA_set0_key)
	__mkcgo__dlsym(DSA_set0_pqg)
	__mkcgo__dlsym(EC_KEY_check_key)
	__mkcgo__dlsym(EC_KEY_free)
	__mkcgo__dlsym(EC_KEY_get0_group)
	__mkcgo__dlsym(EC_KEY_get0_private_key)
	__mkcgo__dlsym(EC_KEY_get0_public_key)
	__mkcgo__dlsym(EC_KEY_new_by_curve_name)
	__mkcgo__dlsym(EC_KEY_set_private_key)
	__mkcgo__dlsym(EC_KEY_set_public_key)
	__mkcgo__dlsym(EC_KEY_set_public_key_affine_coordinates)
	__mkcgo__dlsym(EC_POINT_get_affine_coordinates_GFp)
	__mkcgo__dlsym(ERR_get_error_line)
	__mkcgo__dlsym2(EVP_CIPHER_get_block_size, EVP_CIPHER_block_size)
	__mkcgo__dlsym2(EVP_MD_get_block_size, EVP_MD_block_size)
	__mkcgo__dlsym2(EVP_MD_get_size, EVP_MD_size)
	__mkcgo__dlsym(EVP_PKEY_assign)
	__mkcgo__dlsym(EVP_PKEY_get0_DSA)
	__mkcgo__dlsym(EVP_PKEY_get0_EC_KEY)
	__mkcgo__dlsym(EVP_PKEY_get1_RSA)
	__mkcgo__dlsym2(EVP_PKEY_get_bits, EVP_PKEY_bits)
	__mkcgo__dlsym2(EVP_PKEY_get_size, EVP_PKEY_size)
	__mkcgo__dlsym(EVP_PKEY_set1_EC_KEY)
	__mkcgo__dlsym(FIPS_mode)
	__mkcgo__dlsym(FIPS_mode_set)
	__mkcgo__dlsym(HMAC_CTX_copy)
	__mkcgo__dlsym(HMAC_CTX_free)
	__mkcgo__dlsym(HMAC_CTX_new)
	__mkcgo__dlsym(HMAC_Final)
	__mkcgo__dlsym(HMAC_Init_ex)
	__mkcgo__dlsym(HMAC_Update)
	__mkcgo__dlsym(RSA_free)
	__mkcgo__dlsym(RSA_get0_crt_params)
	__mkcgo__dlsym(RSA_get0_factors)
	__mkcgo__dlsym(RSA_get0_key)
	__mkcgo__dlsym(RSA_new)
	__mkcgo__dlsym(RSA_set0_crt_params)
	__mkcgo__dlsym(RSA_set0_factors)
	__mkcgo__dlsym(RSA_set0_key)
}

void __mkcgo_unload_legacy_1() {
	_g_DSA_free = NULL;
	_g_DSA_generate_key = NULL;
	_g_DSA_get0_key = NULL;
	_g_DSA_get0_pqg = NULL;
	_g_DSA_new = NULL;
	_g_DSA_set0_key = NULL;
	_g_DSA_set0_pqg = NULL;
	_g_EC_KEY_check_key = NULL;
	_g_EC_KEY_free = NULL;
	_g_EC_KEY_get0_group = NULL;
	_g_EC_KEY_get0_private_key = NULL;
	_g_EC_KEY_get0_public_key = NULL;
	_g_EC_KEY_new_by_curve_name = NULL;
	_g_EC_KEY_set_private_key = NULL;
	_g_EC_KEY_set_public_key = NULL;
	_g_EC_KEY_set_public_key_affine_coordinates = NULL;
	_g_EC_POINT_get_affine_coordinates_GFp = NULL;
	_g_ERR_get_error_line = NULL;
	_g_EVP_CIPHER_get_block_size = NULL;
	_g_EVP_MD_get_block_size = NULL;
	_g_EVP_MD_get_size = NULL;
	_g_EVP_PKEY_assign = NULL;
	_g_EVP_PKEY_get0_DSA = NULL;
	_g_EVP_PKEY_get0_EC_KEY = NULL;
	_g_EVP_PKEY_get1_RSA = NULL;
	_g_EVP_PKEY_get_bits = NULL;
	_g_EVP_PKEY_get_size = NULL;
	_g_EVP_PKEY_set1_EC_KEY = NULL;
	_g_FIPS_mode = NULL;
	_g_FIPS_mode_set = NULL;
	_g_HMAC_CTX_copy = NULL;
	_g_HMAC_CTX_free = NULL;
	_g_HMAC_CTX_new = NULL;
	_g_HMAC_Final = NULL;
	_g_HMAC_Init_ex = NULL;
	_g_HMAC_Update = NULL;
	_g_RSA_free = NULL;
	_g_RSA_get0_crt_params = NULL;
	_g_RSA_get0_factors = NULL;
	_g_RSA_get0_key = NULL;
	_g_RSA_new = NULL;
	_g_RSA_set0_crt_params = NULL;
	_g_RSA_set0_factors = NULL;
	_g_RSA_set0_key = NULL;
}

void __mkcgo_load_version(void* handle) {
	__mkcgo__dlsym_nocheck(OPENSSL_version_major, OPENSSL_version_major)
	__mkcgo__dlsym_nocheck(OPENSSL_version_minor, OPENSSL_version_minor)
	__mkcgo__dlsym_nocheck(OPENSSL_version_patch, OPENSSL_version_patch)
	__mkcgo__dlsym_nocheck(OpenSSL_version_num, OpenSSL_version_num)
}

void __mkcgo_unload_version() {
	_g_OPENSSL_version_major = NULL;
	_g_OPENSSL_version_minor = NULL;
	_g_OPENSSL_version_patch = NULL;
	_g_OpenSSL_version_num = NULL;
}

_BIGNUM_PTR _mkcgo_BN_bin2bn(const unsigned char* _arg0, int _arg1, _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_BIGNUM_PTR _ret = _g_BN_bin2bn(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_BN_bn2binpad(const _BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_BN_bn2binpad(_arg0, _arg1, _arg2);
	if (_ret == -1) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_BN_bn2lebinpad(const _BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_BN_bn2lebinpad(_arg0, _arg1, _arg2);
	if (_ret == -1) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_BN_clear(_BIGNUM_PTR _arg0) {
	_g_BN_clear(_arg0);
}

void _mkcgo_BN_clear_free(_BIGNUM_PTR _arg0) {
	_g_BN_clear_free(_arg0);
}

void _mkcgo_BN_free(_BIGNUM_PTR _arg0) {
	_g_BN_free(_arg0);
}

_BIGNUM_PTR _mkcgo_BN_lebin2bn(const unsigned char* _arg0, int _arg1, _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_BIGNUM_PTR _ret = _g_BN_lebin2bn(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_BIGNUM_PTR _mkcgo_BN_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_BIGNUM_PTR _ret = _g_BN_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_BN_num_bits(const _BIGNUM_PTR _arg0) {
	return _g_BN_num_bits(_arg0);
}

void _mkcgo_CRYPTO_free(void* _arg0, const char* _arg1, int _arg2) {
	_g_CRYPTO_free(_arg0, _arg1, _arg2);
}

void* _mkcgo_CRYPTO_malloc(size_t _arg0, const char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	void* _ret = _g_CRYPTO_malloc(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_DSA_free(_DSA_PTR _arg0) {
	_g_DSA_free(_arg0);
}

int _mkcgo_DSA_generate_key(_DSA_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_DSA_generate_key(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_DSA_get0_key(const _DSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2) {
	_g_DSA_get0_key(_arg0, _arg1, _arg2);
}

void _mkcgo_DSA_get0_pqg(const _DSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_DSA_get0_pqg(_arg0, _arg1, _arg2, _arg3);
}

_DSA_PTR _mkcgo_DSA_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_DSA_PTR _ret = _g_DSA_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_DSA_set0_key(_DSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_DSA_set0_key(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_DSA_set0_pqg(_DSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_DSA_set0_pqg(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EC_GROUP_free(_EC_GROUP_PTR _arg0) {
	_g_EC_GROUP_free(_arg0);
}

_EC_GROUP_PTR _mkcgo_EC_GROUP_new_by_curve_name(int _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EC_GROUP_PTR _ret = _g_EC_GROUP_new_by_curve_name(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_KEY_check_key(const _EC_KEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_KEY_check_key(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EC_KEY_free(_EC_KEY_PTR _arg0) {
	_g_EC_KEY_free(_arg0);
}

const _EC_GROUP_PTR _mkcgo_EC_KEY_get0_group(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_group(_arg0);
}

const _BIGNUM_PTR _mkcgo_EC_KEY_get0_private_key(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_private_key(_arg0);
}

const _EC_POINT_PTR _mkcgo_EC_KEY_get0_public_key(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_public_key(_arg0);
}

_EC_KEY_PTR _mkcgo_EC_KEY_new_by_curve_name(int _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EC_KEY_PTR _ret = _g_EC_KEY_new_by_curve_name(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_KEY_set_private_key(_EC_KEY_PTR _arg0, const _BIGNUM_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_KEY_set_private_key(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_KEY_set_public_key(_EC_KEY_PTR _arg0, const _EC_POINT_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_KEY_set_public_key(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_KEY_set_public_key_affine_coordinates(_EC_KEY_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_KEY_set_public_key_affine_coordinates(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EC_POINT_free(_EC_POINT_PTR _arg0) {
	_g_EC_POINT_free(_arg0);
}

int _mkcgo_EC_POINT_get_affine_coordinates_GFp(const _EC_GROUP_PTR _arg0, const _EC_POINT_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3, _BN_CTX_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_POINT_get_affine_coordinates_GFp(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_POINT_mul(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const _BIGNUM_PTR _arg2, const _EC_POINT_PTR _arg3, const _BIGNUM_PTR _arg4, _BN_CTX_PTR _arg5, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_POINT_mul(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EC_POINT_PTR _mkcgo_EC_POINT_new(const _EC_GROUP_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EC_POINT_PTR _ret = _g_EC_POINT_new(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_POINT_oct2point(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const unsigned char* _arg2, size_t _arg3, _BN_CTX_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_POINT_oct2point(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

size_t _mkcgo_EC_POINT_point2oct(const _EC_GROUP_PTR _arg0, const _EC_POINT_PTR _arg1, point_conversion_form_t _arg2, unsigned char* _arg3, size_t _arg4, _BN_CTX_PTR _arg5, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	size_t _ret = _g_EC_POINT_point2oct(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EC_POINT_set_affine_coordinates(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const _BIGNUM_PTR _arg2, const _BIGNUM_PTR _arg3, _BN_CTX_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EC_POINT_set_affine_coordinates(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_ERR_clear_error(void) {
	_g_ERR_clear_error();
}

void _mkcgo_ERR_error_string_n(unsigned long _arg0, char* _arg1, size_t _arg2) {
	_g_ERR_error_string_n(_arg0, _arg1, _arg2);
}

unsigned long _mkcgo_ERR_get_error_all(const char** _arg0, int* _arg1, const char** _arg2, const char** _arg3, int* _arg4) {
	return _g_ERR_get_error_all(_arg0, _arg1, _arg2, _arg3, _arg4);
}

unsigned long _mkcgo_ERR_get_error_line(const char** _arg0, int* _arg1) {
	return _g_ERR_get_error_line(_arg0, _arg1);
}

int _mkcgo_EVP_CIPHER_CTX_ctrl(_EVP_CIPHER_CTX_PTR _arg0, int _arg1, int _arg2, void* _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_CIPHER_CTX_ctrl(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_CIPHER_CTX_free(_EVP_CIPHER_CTX_PTR _arg0) {
	_g_EVP_CIPHER_CTX_free(_arg0);
}

_EVP_CIPHER_CTX_PTR _mkcgo_EVP_CIPHER_CTX_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_CIPHER_CTX_PTR _ret = _g_EVP_CIPHER_CTX_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_CIPHER_CTX_set_key_length(_EVP_CIPHER_CTX_PTR _arg0, int _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_CIPHER_CTX_set_key_length(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_CIPHER_CTX_set_padding(_EVP_CIPHER_CTX_PTR _arg0, int _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_CIPHER_CTX_set_padding(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_CIPHER_PTR _mkcgo_EVP_CIPHER_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_CIPHER_PTR _ret = _g_EVP_CIPHER_fetch(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

const char* _mkcgo_EVP_CIPHER_get0_name(const _EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get0_name(_arg0);
}

int _mkcgo_EVP_CIPHER_get_block_size(const _EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get_block_size(_arg0);
}

int _mkcgo_EVP_CipherInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4, int _arg5, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_CipherInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_CipherUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_CipherUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DecryptFinal_ex(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DecryptFinal_ex(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DecryptInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DecryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DecryptUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DecryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_Digest(const void* _arg0, size_t _arg1, unsigned char* _arg2, unsigned int* _arg3, const _EVP_MD_PTR _arg4, _ENGINE_PTR _arg5, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_Digest(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestFinal_ex(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestFinal_ex(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestInit(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestInit(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestInit_ex(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_PTR _arg1, _ENGINE_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestInit_ex(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestSign(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestSign(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestSignFinal(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestSignFinal(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestSignInit(_EVP_MD_CTX_PTR _arg0, _EVP_PKEY_CTX_PTR* _arg1, const _EVP_MD_PTR _arg2, _ENGINE_PTR _arg3, _EVP_PKEY_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestSignInit(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestUpdate(_EVP_MD_CTX_PTR _arg0, const void* _arg1, size_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestUpdate(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestVerify(_EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestVerify(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestVerifyFinal(_EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestVerifyFinal(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_DigestVerifyInit(_EVP_MD_CTX_PTR _arg0, _EVP_PKEY_CTX_PTR* _arg1, const _EVP_MD_PTR _arg2, _ENGINE_PTR _arg3, _EVP_PKEY_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_DigestVerifyInit(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_EncryptFinal_ex(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_EncryptFinal_ex(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_EncryptInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_EncryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_EncryptUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_EncryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_KDF_CTX_free(_EVP_KDF_CTX_PTR _arg0) {
	_g_EVP_KDF_CTX_free(_arg0);
}

size_t _mkcgo_EVP_KDF_CTX_get_kdf_size(_EVP_KDF_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	size_t _ret = _g_EVP_KDF_CTX_get_kdf_size(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_KDF_CTX_PTR _mkcgo_EVP_KDF_CTX_new(_EVP_KDF_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_KDF_CTX_PTR _ret = _g_EVP_KDF_CTX_new(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_KDF_CTX_set_params(_EVP_KDF_CTX_PTR _arg0, const _OSSL_PARAM_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_KDF_CTX_set_params(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_KDF_derive(_EVP_KDF_CTX_PTR _arg0, unsigned char* _arg1, size_t _arg2, const _OSSL_PARAM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_KDF_derive(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_KDF_PTR _mkcgo_EVP_KDF_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_KDF_PTR _ret = _g_EVP_KDF_fetch(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_KDF_free(_EVP_KDF_PTR _arg0) {
	_g_EVP_KDF_free(_arg0);
}

_EVP_MAC_CTX_PTR _mkcgo_EVP_MAC_CTX_dup(const _EVP_MAC_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_MAC_CTX_PTR _ret = _g_EVP_MAC_CTX_dup(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_MAC_CTX_free(_EVP_MAC_CTX_PTR _arg0) {
	_g_EVP_MAC_CTX_free(_arg0);
}

_EVP_MAC_CTX_PTR _mkcgo_EVP_MAC_CTX_new(_EVP_MAC_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_MAC_CTX_PTR _ret = _g_EVP_MAC_CTX_new(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MAC_CTX_set_params(_EVP_MAC_CTX_PTR _arg0, const _OSSL_PARAM_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MAC_CTX_set_params(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_MAC_PTR _mkcgo_EVP_MAC_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_MAC_PTR _ret = _g_EVP_MAC_fetch(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MAC_final(_EVP_MAC_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MAC_final(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MAC_init(_EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const _OSSL_PARAM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MAC_init(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MAC_update(_EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MAC_update(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MD_CTX_copy(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_CTX_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MD_CTX_copy(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MD_CTX_copy_ex(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_CTX_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MD_CTX_copy_ex(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_MD_CTX_free(_EVP_MD_CTX_PTR _arg0) {
	_g_EVP_MD_CTX_free(_arg0);
}

int _mkcgo_EVP_MD_CTX_get_params(_EVP_MD_CTX_PTR _arg0, _OSSL_PARAM_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MD_CTX_get_params(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

const _OSSL_PARAM_PTR _mkcgo_EVP_MD_CTX_gettable_params(_EVP_MD_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	const _OSSL_PARAM_PTR _ret = _g_EVP_MD_CTX_gettable_params(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_MD_CTX_PTR _mkcgo_EVP_MD_CTX_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_MD_CTX_PTR _ret = _g_EVP_MD_CTX_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_MD_CTX_set_params(_EVP_MD_CTX_PTR _arg0, const _OSSL_PARAM_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_MD_CTX_set_params(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

const _OSSL_PARAM_PTR _mkcgo_EVP_MD_CTX_settable_params(_EVP_MD_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	const _OSSL_PARAM_PTR _ret = _g_EVP_MD_CTX_settable_params(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_MD_PTR _mkcgo_EVP_MD_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_MD_PTR _ret = _g_EVP_MD_fetch(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_MD_free(_EVP_MD_PTR _arg0) {
	_g_EVP_MD_free(_arg0);
}

const char* _mkcgo_EVP_MD_get0_name(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_name(_arg0);
}

const _OSSL_PROVIDER_PTR _mkcgo_EVP_MD_get0_provider(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_provider(_arg0);
}

int _mkcgo_EVP_MD_get_block_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_block_size(_arg0);
}

int _mkcgo_EVP_MD_get_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_size(_arg0);
}

int _mkcgo_EVP_MD_get_type(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_type(_arg0);
}

int _mkcgo_EVP_PKEY_CTX_add1_hkdf_info(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_add1_hkdf_info(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_ctrl(_EVP_PKEY_CTX_PTR _arg0, int _arg1, int _arg2, int _arg3, int _arg4, void* _arg5, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_ctrl(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_PKEY_CTX_free(_EVP_PKEY_CTX_PTR _arg0) {
	_g_EVP_PKEY_CTX_free(_arg0);
}

_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new(_EVP_PKEY_PTR _arg0, _ENGINE_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_CTX_PTR _ret = _g_EVP_PKEY_CTX_new(_arg0, _arg1);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new_from_pkey(_OSSL_LIB_CTX_PTR _arg0, _EVP_PKEY_PTR _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_CTX_PTR _ret = _g_EVP_PKEY_CTX_new_from_pkey(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new_id(int _arg0, _ENGINE_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_CTX_PTR _ret = _g_EVP_PKEY_CTX_new_id(_arg0, _arg1);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_set0_rsa_oaep_label(_EVP_PKEY_CTX_PTR _arg0, void* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_set0_rsa_oaep_label(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_set1_hkdf_key(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_set1_hkdf_key(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_set1_hkdf_salt(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_set1_hkdf_salt(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_set_hkdf_md(_EVP_PKEY_CTX_PTR _arg0, const _EVP_MD_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_set_hkdf_md(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_CTX_set_hkdf_mode(_EVP_PKEY_CTX_PTR _arg0, int _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_CTX_set_hkdf_mode(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_EC(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, const char* _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_Q_keygen(_arg0, _arg1, _arg2, _arg3);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_ED25519(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_Q_keygen(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_RSA(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_Q_keygen(_arg0, _arg1, _arg2, _arg3);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_assign(_EVP_PKEY_PTR _arg0, int _arg1, void* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_assign(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_decrypt(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_decrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_decrypt_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_decrypt_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_derive(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_derive(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_derive_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_derive_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_derive_set_peer(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_derive_set_peer(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_encrypt(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_encrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_encrypt_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_encrypt_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_PKEY_free(_EVP_PKEY_PTR _arg0) {
	_g_EVP_PKEY_free(_arg0);
}

int _mkcgo_EVP_PKEY_fromdata(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1, int _arg2, _OSSL_PARAM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_fromdata(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_fromdata_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_fromdata_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_DSA_PTR _mkcgo_EVP_PKEY_get0_DSA(_EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_DSA_PTR _ret = _g_EVP_PKEY_get0_DSA(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EC_KEY_PTR _mkcgo_EVP_PKEY_get0_EC_KEY(_EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EC_KEY_PTR _ret = _g_EVP_PKEY_get0_EC_KEY(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_RSA_PTR _mkcgo_EVP_PKEY_get1_RSA(_EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_RSA_PTR _ret = _g_EVP_PKEY_get1_RSA(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

size_t _mkcgo_EVP_PKEY_get1_encoded_public_key(_EVP_PKEY_PTR _arg0, unsigned char** _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	size_t _ret = _g_EVP_PKEY_get1_encoded_public_key(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_get_bits(const _EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_get_bits(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_get_bn_param(const _EVP_PKEY_PTR _arg0, const char* _arg1, _BIGNUM_PTR* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_get_bn_param(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_get_raw_private_key(const _EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_get_raw_private_key(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_get_raw_public_key(const _EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_get_raw_public_key(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_get_size(const _EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_get_size(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_keygen(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_keygen(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_keygen_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_keygen_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new_raw_private_key(int _arg0, _ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_new_raw_private_key(_arg0, _arg1, _arg2, _arg3);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new_raw_public_key(int _arg0, _ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_PKEY_PTR _ret = _g_EVP_PKEY_new_raw_public_key(_arg0, _arg1, _arg2, _arg3);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_paramgen(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_paramgen(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_paramgen_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_paramgen_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_private_check(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_private_check(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_public_check_quick(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_public_check_quick(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_set1_EC_KEY(_EVP_PKEY_PTR _arg0, _EC_KEY_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_set1_EC_KEY(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_set1_encoded_public_key(_EVP_PKEY_PTR _arg0, const unsigned char* _arg1, size_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_set1_encoded_public_key(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_sign(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_sign(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_sign_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_sign_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_up_ref(_EVP_PKEY_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_up_ref(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_verify(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_verify(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_PKEY_verify_init(_EVP_PKEY_CTX_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_PKEY_verify_init(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_EVP_SIGNATURE_PTR _mkcgo_EVP_SIGNATURE_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_EVP_SIGNATURE_PTR _ret = _g_EVP_SIGNATURE_fetch(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_EVP_SIGNATURE_free(_EVP_SIGNATURE_PTR _arg0) {
	_g_EVP_SIGNATURE_free(_arg0);
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_cbc(void) {
	return _g_EVP_aes_128_cbc();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_ctr(void) {
	return _g_EVP_aes_128_ctr();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_ecb(void) {
	return _g_EVP_aes_128_ecb();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_gcm(void) {
	return _g_EVP_aes_128_gcm();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_cbc(void) {
	return _g_EVP_aes_192_cbc();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_ctr(void) {
	return _g_EVP_aes_192_ctr();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_ecb(void) {
	return _g_EVP_aes_192_ecb();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_gcm(void) {
	return _g_EVP_aes_192_gcm();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_cbc(void) {
	return _g_EVP_aes_256_cbc();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_ctr(void) {
	return _g_EVP_aes_256_ctr();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_ecb(void) {
	return _g_EVP_aes_256_ecb();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_gcm(void) {
	return _g_EVP_aes_256_gcm();
}

int _mkcgo_EVP_default_properties_enable_fips(_OSSL_LIB_CTX_PTR _arg0, int _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_EVP_default_properties_enable_fips(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_EVP_default_properties_is_fips_enabled(_OSSL_LIB_CTX_PTR _arg0) {
	return _g_EVP_default_properties_is_fips_enabled(_arg0);
}

const _EVP_CIPHER_PTR _mkcgo_EVP_des_cbc(void) {
	return _g_EVP_des_cbc();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_des_ecb(void) {
	return _g_EVP_des_ecb();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_des_ede3_cbc(void) {
	return _g_EVP_des_ede3_cbc();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_des_ede3_ecb(void) {
	return _g_EVP_des_ede3_ecb();
}

const _EVP_MD_PTR _mkcgo_EVP_md4(void) {
	return _g_EVP_md4();
}

const _EVP_MD_PTR _mkcgo_EVP_md5(void) {
	return _g_EVP_md5();
}

const _EVP_MD_PTR _mkcgo_EVP_md5_sha1(void) {
	return _g_EVP_md5_sha1();
}

const _EVP_CIPHER_PTR _mkcgo_EVP_rc4(void) {
	return _g_EVP_rc4();
}

const _EVP_MD_PTR _mkcgo_EVP_ripemd160(void) {
	return _g_EVP_ripemd160();
}

const _EVP_MD_PTR _mkcgo_EVP_sha1(void) {
	return _g_EVP_sha1();
}

const _EVP_MD_PTR _mkcgo_EVP_sha224(void) {
	return _g_EVP_sha224();
}

const _EVP_MD_PTR _mkcgo_EVP_sha256(void) {
	return _g_EVP_sha256();
}

const _EVP_MD_PTR _mkcgo_EVP_sha384(void) {
	return _g_EVP_sha384();
}

const _EVP_MD_PTR _mkcgo_EVP_sha3_224(void) {
	return _g_EVP_sha3_224();
}

const _EVP_MD_PTR _mkcgo_EVP_sha3_256(void) {
	return _g_EVP_sha3_256();
}

const _EVP_MD_PTR _mkcgo_EVP_sha3_384(void) {
	return _g_EVP_sha3_384();
}

const _EVP_MD_PTR _mkcgo_EVP_sha3_512(void) {
	return _g_EVP_sha3_512();
}

const _EVP_MD_PTR _mkcgo_EVP_sha512(void) {
	return _g_EVP_sha512();
}

const _EVP_MD_PTR _mkcgo_EVP_sha512_224(void) {
	return _g_EVP_sha512_224();
}

const _EVP_MD_PTR _mkcgo_EVP_sha512_256(void) {
	return _g_EVP_sha512_256();
}

int _mkcgo_FIPS_mode(void) {
	return _g_FIPS_mode();
}

int _mkcgo_FIPS_mode_set(int _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_FIPS_mode_set(_arg0);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_HMAC_CTX_copy(_HMAC_CTX_PTR _arg0, _HMAC_CTX_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_HMAC_CTX_copy(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_HMAC_CTX_free(_HMAC_CTX_PTR _arg0) {
	_g_HMAC_CTX_free(_arg0);
}

_HMAC_CTX_PTR _mkcgo_HMAC_CTX_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_HMAC_CTX_PTR _ret = _g_HMAC_CTX_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_HMAC_Final(_HMAC_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_HMAC_Final(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_HMAC_Init_ex(_HMAC_CTX_PTR _arg0, const void* _arg1, int _arg2, const _EVP_MD_PTR _arg3, _ENGINE_PTR _arg4, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_HMAC_Init_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_HMAC_Update(_HMAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_HMAC_Update(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

const char* _mkcgo_OBJ_nid2sn(int _arg0) {
	return _g_OBJ_nid2sn(_arg0);
}

void _mkcgo_OPENSSL_init(void) {
	_g_OPENSSL_init();
}

int _mkcgo_OPENSSL_init_crypto(uint64_t _arg0, const _OPENSSL_INIT_SETTINGS_PTR _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_OPENSSL_init_crypto(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_available_OPENSSL_version_major() {
	return _g_OPENSSL_version_major != NULL;
}

unsigned int _mkcgo_OPENSSL_version_major(void) {
	return _g_OPENSSL_version_major();
}

int _mkcgo_available_OPENSSL_version_minor() {
	return _g_OPENSSL_version_minor != NULL;
}

unsigned int _mkcgo_OPENSSL_version_minor(void) {
	return _g_OPENSSL_version_minor();
}

int _mkcgo_available_OPENSSL_version_patch() {
	return _g_OPENSSL_version_patch != NULL;
}

unsigned int _mkcgo_OPENSSL_version_patch(void) {
	return _g_OPENSSL_version_patch();
}

void _mkcgo_OSSL_PARAM_BLD_free(_OSSL_PARAM_BLD_PTR _arg0) {
	_g_OSSL_PARAM_BLD_free(_arg0);
}

_OSSL_PARAM_BLD_PTR _mkcgo_OSSL_PARAM_BLD_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_OSSL_PARAM_BLD_PTR _ret = _g_OSSL_PARAM_BLD_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_OSSL_PARAM_BLD_push_BN(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_OSSL_PARAM_BLD_push_BN(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_OSSL_PARAM_BLD_push_int32(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, int32_t _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_OSSL_PARAM_BLD_push_int32(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_OSSL_PARAM_BLD_push_octet_string(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const void* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_OSSL_PARAM_BLD_push_octet_string(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_OSSL_PARAM_BLD_push_utf8_string(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_OSSL_PARAM_BLD_push_utf8_string(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

_OSSL_PARAM_PTR _mkcgo_OSSL_PARAM_BLD_to_param(_OSSL_PARAM_BLD_PTR _arg0, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_OSSL_PARAM_PTR _ret = _g_OSSL_PARAM_BLD_to_param(_arg0);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_OSSL_PARAM_free(_OSSL_PARAM_PTR _arg0) {
	_g_OSSL_PARAM_free(_arg0);
}

const _OSSL_PARAM_PTR _mkcgo_OSSL_PARAM_locate_const(const _OSSL_PARAM_PTR _arg0, const char* _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	const _OSSL_PARAM_PTR _ret = _g_OSSL_PARAM_locate_const(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_OSSL_PROVIDER_available(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1) {
	return _g_OSSL_PROVIDER_available(_arg0, _arg1);
}

const char* _mkcgo_OSSL_PROVIDER_get0_name(const _OSSL_PROVIDER_PTR _arg0) {
	return _g_OSSL_PROVIDER_get0_name(_arg0);
}

_OSSL_PROVIDER_PTR _mkcgo_OSSL_PROVIDER_try_load(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, int _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_OSSL_PROVIDER_PTR _ret = _g_OSSL_PROVIDER_try_load(_arg0, _arg1, _arg2);
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

const char* _mkcgo_OpenSSL_version(int _arg0) {
	return _g_OpenSSL_version(_arg0);
}

int _mkcgo_available_OpenSSL_version_num() {
	return _g_OpenSSL_version_num != NULL;
}

unsigned long _mkcgo_OpenSSL_version_num(void) {
	return _g_OpenSSL_version_num();
}

int _mkcgo_PKCS5_PBKDF2_HMAC(const char* _arg0, int _arg1, const unsigned char* _arg2, int _arg3, int _arg4, const _EVP_MD_PTR _arg5, int _arg6, unsigned char* _arg7, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_PKCS5_PBKDF2_HMAC(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_RAND_bytes(unsigned char* _arg0, int _arg1, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_RAND_bytes(_arg0, _arg1);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

void _mkcgo_RSA_free(_RSA_PTR _arg0) {
	_g_RSA_free(_arg0);
}

void _mkcgo_RSA_get0_crt_params(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_RSA_get0_crt_params(_arg0, _arg1, _arg2, _arg3);
}

void _mkcgo_RSA_get0_factors(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2) {
	_g_RSA_get0_factors(_arg0, _arg1, _arg2);
}

void _mkcgo_RSA_get0_key(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_RSA_get0_key(_arg0, _arg1, _arg2, _arg3);
}

_RSA_PTR _mkcgo_RSA_new(mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	_RSA_PTR _ret = _g_RSA_new();
	if (_ret == NULL) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_RSA_set0_crt_params(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_RSA_set0_crt_params(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_RSA_set0_factors(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_RSA_set0_factors(_arg0, _arg1, _arg2);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

int _mkcgo_RSA_set0_key(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3, mkcgo_err_state *_err_state) {
	mkcgo_err_clear();
	int _ret = _g_RSA_set0_key(_arg0, _arg1, _arg2, _arg3);
	if (_ret <= 0) *_err_state = mkcgo_err_retrieve();
	return _ret;
}

