// Code generated by mkcgo. DO NOT EDIT.

#ifndef MKCGO_H // only include this header once
#define MKCGO_H

#include <stdlib.h>
#include <stdint.h>

typedef void* _OPENSSL_INIT_SETTINGS_PTR;
typedef void* _OSSL_LIB_CTX_PTR;
typedef void* _OSSL_PROVIDER_PTR;
typedef void* _ENGINE_PTR;
typedef void* _EVP_PKEY_PTR;
typedef void* _EVP_PKEY_CTX_PTR;
typedef void* _EVP_MD_PTR;
typedef void* _EVP_MD_CTX_PTR;
typedef void* _HMAC_CTX_PTR;
typedef void* _EVP_CIPHER_PTR;
typedef void* _EVP_CIPHER_CTX_PTR;
typedef void* _EC_KEY_PTR;
typedef void* _EC_POINT_PTR;
typedef void* _EC_GROUP_PTR;
typedef void* _RSA_PTR;
typedef void* _BIGNUM_PTR;
typedef void* _BN_CTX_PTR;
typedef void* _EVP_MAC_PTR;
typedef void* _EVP_MAC_CTX_PTR;
typedef void* _OSSL_PARAM_BLD_PTR;
typedef void* _OSSL_PARAM_PTR;
typedef void* _EVP_SIGNATURE_PTR;
typedef void* _DSA_PTR;
typedef void* _EVP_KDF_PTR;
typedef void* _EVP_KDF_CTX_PTR;
typedef int point_conversion_form_t;

enum {
	_POINT_CONVERSION_UNCOMPRESSED = 4,
	_OPENSSL_INIT_LOAD_CRYPTO_STRINGS = 0x00000002,
	_OPENSSL_INIT_ADD_ALL_CIPHERS = 0x00000004,
	_OPENSSL_INIT_ADD_ALL_DIGESTS = 0x00000008,
	_OPENSSL_INIT_LOAD_CONFIG = 0x00000040,
	_EVP_CTRL_GCM_GET_TAG = 0x10,
	_EVP_CTRL_GCM_SET_TAG = 0x11,
	_EVP_PKEY_CTRL_MD = 1,
	_EVP_PKEY_RSA = 6,
	_EVP_PKEY_EC = 408,
	_EVP_PKEY_TLS1_PRF = 1021,
	_EVP_PKEY_HKDF = 1036,
	_EVP_PKEY_ED25519 = 1087,
	_EVP_PKEY_DSA = 116,
	_EVP_PKEY_OP_DERIVE = (1 << 10),
	_EVP_MAX_MD_SIZE = 64,
	_EVP_PKEY_PUBLIC_KEY = 0x86,
	_EVP_PKEY_KEYPAIR = 0x87,
	_EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID = 0x1001,
	_EVP_KDF_HKDF_MODE_EXTRACT_ONLY = 1,
	_EVP_KDF_HKDF_MODE_EXPAND_ONLY = 2,
	_EVP_PKEY_CTRL_TLS_MD = 0x1000,
	_EVP_PKEY_CTRL_TLS_SECRET = 0x1001,
	_EVP_PKEY_CTRL_TLS_SEED = 0x1002,
	_EVP_PKEY_CTRL_HKDF_MD = 0x1003,
	_EVP_PKEY_CTRL_HKDF_SALT = 0x1004,
	_EVP_PKEY_CTRL_HKDF_KEY = 0x1005,
	_EVP_PKEY_CTRL_HKDF_INFO = 0x1006,
	_EVP_PKEY_CTRL_HKDF_MODE = 0x1007,
	_NID_X9_62_prime256v1 = 415,
	_NID_secp224r1 = 713,
	_NID_secp384r1 = 715,
	_NID_secp521r1 = 716,
	_RSA_PKCS1_PADDING = 1,
	_RSA_NO_PADDING = 3,
	_RSA_PKCS1_OAEP_PADDING = 4,
	_RSA_PKCS1_PSS_PADDING = 6,
	_RSA_PSS_SALTLEN_DIGEST = -1,
	_RSA_PSS_SALTLEN_AUTO = -2,
	_RSA_PSS_SALTLEN_MAX_SIGN = -2,
	_RSA_PSS_SALTLEN_MAX = -3,
	_EVP_PKEY_CTRL_RSA_PADDING = 0x1001,
	_EVP_PKEY_CTRL_RSA_PSS_SALTLEN = 0x1002,
	_EVP_PKEY_CTRL_RSA_KEYGEN_BITS = 0x1003,
	_EVP_PKEY_CTRL_RSA_MGF1_MD = 0x1005,
	_EVP_PKEY_CTRL_RSA_OAEP_MD = 0x1009,
	_EVP_PKEY_CTRL_RSA_OAEP_LABEL = 0x100A,
	_EVP_PKEY_CTRL_DSA_PARAMGEN_BITS = 0x1001,
	_EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS = 0x1002,
	_OSSL_PARAM_INTEGER = 1,
	_OSSL_PARAM_OCTET_STRING = 5,
};

typedef void* mkcgo_err_state;
mkcgo_err_state mkcgo_err_retrieve();
void mkcgo_err_free(mkcgo_err_state);
void mkcgo_err_clear();

void __mkcgo_load_(void* handle);
void __mkcgo_unload_();
void __mkcgo_load_111(void* handle);
void __mkcgo_unload_111();
void __mkcgo_load_3(void* handle);
void __mkcgo_unload_3();
void __mkcgo_load_init_1(void* handle);
void __mkcgo_unload_init_1();
void __mkcgo_load_init_3(void* handle);
void __mkcgo_unload_init_3();
void __mkcgo_load_legacy_1(void* handle);
void __mkcgo_unload_legacy_1();
void __mkcgo_load_version(void* handle);
void __mkcgo_unload_version();

int _mkcgo_available_OPENSSL_version_major();
int _mkcgo_available_OPENSSL_version_minor();
int _mkcgo_available_OPENSSL_version_patch();
int _mkcgo_available_OpenSSL_version_num();

_BIGNUM_PTR _mkcgo_BN_bin2bn(const unsigned char*, int, _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_BN_bn2binpad(const _BIGNUM_PTR, unsigned char*, int, mkcgo_err_state *);
int _mkcgo_BN_bn2lebinpad(const _BIGNUM_PTR, unsigned char*, int, mkcgo_err_state *);
void _mkcgo_BN_clear(_BIGNUM_PTR);
void _mkcgo_BN_clear_free(_BIGNUM_PTR);
void _mkcgo_BN_free(_BIGNUM_PTR);
_BIGNUM_PTR _mkcgo_BN_lebin2bn(const unsigned char*, int, _BIGNUM_PTR, mkcgo_err_state *);
_BIGNUM_PTR _mkcgo_BN_new(mkcgo_err_state *);
int _mkcgo_BN_num_bits(const _BIGNUM_PTR);
void _mkcgo_CRYPTO_free(void*, const char*, int);
void* _mkcgo_CRYPTO_malloc(size_t, const char*, int, mkcgo_err_state *);
void _mkcgo_DSA_free(_DSA_PTR);
int _mkcgo_DSA_generate_key(_DSA_PTR, mkcgo_err_state *);
void _mkcgo_DSA_get0_key(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void _mkcgo_DSA_get0_pqg(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_DSA_PTR _mkcgo_DSA_new(mkcgo_err_state *);
int _mkcgo_DSA_set0_key(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_DSA_set0_pqg(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);
void _mkcgo_EC_GROUP_free(_EC_GROUP_PTR);
_EC_GROUP_PTR _mkcgo_EC_GROUP_new_by_curve_name(int, mkcgo_err_state *);
int _mkcgo_EC_KEY_check_key(const _EC_KEY_PTR, mkcgo_err_state *);
void _mkcgo_EC_KEY_free(_EC_KEY_PTR);
const _EC_GROUP_PTR _mkcgo_EC_KEY_get0_group(const _EC_KEY_PTR);
const _BIGNUM_PTR _mkcgo_EC_KEY_get0_private_key(const _EC_KEY_PTR);
const _EC_POINT_PTR _mkcgo_EC_KEY_get0_public_key(const _EC_KEY_PTR);
_EC_KEY_PTR _mkcgo_EC_KEY_new_by_curve_name(int, mkcgo_err_state *);
int _mkcgo_EC_KEY_set_private_key(_EC_KEY_PTR, const _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_EC_KEY_set_public_key(_EC_KEY_PTR, const _EC_POINT_PTR, mkcgo_err_state *);
int _mkcgo_EC_KEY_set_public_key_affine_coordinates(_EC_KEY_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);
void _mkcgo_EC_POINT_free(_EC_POINT_PTR);
int _mkcgo_EC_POINT_get_affine_coordinates_GFp(const _EC_GROUP_PTR, const _EC_POINT_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BN_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EC_POINT_mul(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _EC_POINT_PTR, const _BIGNUM_PTR, _BN_CTX_PTR, mkcgo_err_state *);
_EC_POINT_PTR _mkcgo_EC_POINT_new(const _EC_GROUP_PTR, mkcgo_err_state *);
int _mkcgo_EC_POINT_oct2point(const _EC_GROUP_PTR, _EC_POINT_PTR, const unsigned char*, size_t, _BN_CTX_PTR, mkcgo_err_state *);
size_t _mkcgo_EC_POINT_point2oct(const _EC_GROUP_PTR, const _EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, _BN_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EC_POINT_set_affine_coordinates(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _BIGNUM_PTR, _BN_CTX_PTR, mkcgo_err_state *);
void _mkcgo_ERR_clear_error(void);
void _mkcgo_ERR_error_string_n(unsigned long, char*, size_t);
unsigned long _mkcgo_ERR_get_error_all(const char**, int*, const char**, const char**, int*);
unsigned long _mkcgo_ERR_get_error_line(const char**, int*);
int _mkcgo_EVP_CIPHER_CTX_ctrl(_EVP_CIPHER_CTX_PTR, int, int, void*, mkcgo_err_state *);
void _mkcgo_EVP_CIPHER_CTX_free(_EVP_CIPHER_CTX_PTR);
_EVP_CIPHER_CTX_PTR _mkcgo_EVP_CIPHER_CTX_new(mkcgo_err_state *);
int _mkcgo_EVP_CIPHER_CTX_set_key_length(_EVP_CIPHER_CTX_PTR, int, mkcgo_err_state *);
int _mkcgo_EVP_CIPHER_CTX_set_padding(_EVP_CIPHER_CTX_PTR, int, mkcgo_err_state *);
_EVP_CIPHER_PTR _mkcgo_EVP_CIPHER_fetch(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
const char* _mkcgo_EVP_CIPHER_get0_name(const _EVP_CIPHER_PTR);
int _mkcgo_EVP_CIPHER_get_block_size(const _EVP_CIPHER_PTR);
int _mkcgo_EVP_CipherInit_ex(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_CipherUpdate(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_DecryptFinal_ex(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, mkcgo_err_state *);
int _mkcgo_EVP_DecryptInit_ex(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, mkcgo_err_state *);
int _mkcgo_EVP_DecryptUpdate(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_Digest(const void*, size_t, unsigned char*, unsigned int*, const _EVP_MD_PTR, _ENGINE_PTR, mkcgo_err_state *);
int _mkcgo_EVP_DigestFinal_ex(_EVP_MD_CTX_PTR, unsigned char*, unsigned int*, mkcgo_err_state *);
int _mkcgo_EVP_DigestInit(_EVP_MD_CTX_PTR, const _EVP_MD_PTR, mkcgo_err_state *);
int _mkcgo_EVP_DigestInit_ex(_EVP_MD_CTX_PTR, const _EVP_MD_PTR, _ENGINE_PTR, mkcgo_err_state *);
int _mkcgo_EVP_DigestSign(_EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_DigestSignFinal(_EVP_MD_CTX_PTR, unsigned char*, size_t*, mkcgo_err_state *);
int _mkcgo_EVP_DigestSignInit(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_DigestUpdate(_EVP_MD_CTX_PTR, const void*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_DigestVerify(_EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_DigestVerifyFinal(_EVP_MD_CTX_PTR, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_DigestVerifyInit(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_EncryptFinal_ex(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, mkcgo_err_state *);
int _mkcgo_EVP_EncryptInit_ex(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, mkcgo_err_state *);
int _mkcgo_EVP_EncryptUpdate(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int, mkcgo_err_state *);
void _mkcgo_EVP_KDF_CTX_free(_EVP_KDF_CTX_PTR);
size_t _mkcgo_EVP_KDF_CTX_get_kdf_size(_EVP_KDF_CTX_PTR, mkcgo_err_state *);
_EVP_KDF_CTX_PTR _mkcgo_EVP_KDF_CTX_new(_EVP_KDF_PTR, mkcgo_err_state *);
int _mkcgo_EVP_KDF_CTX_set_params(_EVP_KDF_CTX_PTR, const _OSSL_PARAM_PTR, mkcgo_err_state *);
int _mkcgo_EVP_KDF_derive(_EVP_KDF_CTX_PTR, unsigned char*, size_t, const _OSSL_PARAM_PTR, mkcgo_err_state *);
_EVP_KDF_PTR _mkcgo_EVP_KDF_fetch(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
void _mkcgo_EVP_KDF_free(_EVP_KDF_PTR);
_EVP_MAC_CTX_PTR _mkcgo_EVP_MAC_CTX_dup(const _EVP_MAC_CTX_PTR, mkcgo_err_state *);
void _mkcgo_EVP_MAC_CTX_free(_EVP_MAC_CTX_PTR);
_EVP_MAC_CTX_PTR _mkcgo_EVP_MAC_CTX_new(_EVP_MAC_PTR, mkcgo_err_state *);
int _mkcgo_EVP_MAC_CTX_set_params(_EVP_MAC_CTX_PTR, const _OSSL_PARAM_PTR, mkcgo_err_state *);
_EVP_MAC_PTR _mkcgo_EVP_MAC_fetch(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
int _mkcgo_EVP_MAC_final(_EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_MAC_init(_EVP_MAC_CTX_PTR, const unsigned char*, size_t, const _OSSL_PARAM_PTR, mkcgo_err_state *);
int _mkcgo_EVP_MAC_update(_EVP_MAC_CTX_PTR, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_MD_CTX_copy(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_MD_CTX_copy_ex(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR, mkcgo_err_state *);
void _mkcgo_EVP_MD_CTX_free(_EVP_MD_CTX_PTR);
int _mkcgo_EVP_MD_CTX_get_params(_EVP_MD_CTX_PTR, _OSSL_PARAM_PTR, mkcgo_err_state *);
const _OSSL_PARAM_PTR _mkcgo_EVP_MD_CTX_gettable_params(_EVP_MD_CTX_PTR, mkcgo_err_state *);
_EVP_MD_CTX_PTR _mkcgo_EVP_MD_CTX_new(mkcgo_err_state *);
int _mkcgo_EVP_MD_CTX_set_params(_EVP_MD_CTX_PTR, const _OSSL_PARAM_PTR, mkcgo_err_state *);
const _OSSL_PARAM_PTR _mkcgo_EVP_MD_CTX_settable_params(_EVP_MD_CTX_PTR, mkcgo_err_state *);
_EVP_MD_PTR _mkcgo_EVP_MD_fetch(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
void _mkcgo_EVP_MD_free(_EVP_MD_PTR);
const char* _mkcgo_EVP_MD_get0_name(const _EVP_MD_PTR);
const _OSSL_PROVIDER_PTR _mkcgo_EVP_MD_get0_provider(const _EVP_MD_PTR);
int _mkcgo_EVP_MD_get_block_size(const _EVP_MD_PTR);
int _mkcgo_EVP_MD_get_size(const _EVP_MD_PTR);
int _mkcgo_EVP_MD_get_type(const _EVP_MD_PTR);
int _mkcgo_EVP_PKEY_CTX_add1_hkdf_info(_EVP_PKEY_CTX_PTR, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_ctrl(_EVP_PKEY_CTX_PTR, int, int, int, int, void*, mkcgo_err_state *);
void _mkcgo_EVP_PKEY_CTX_free(_EVP_PKEY_CTX_PTR);
_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new(_EVP_PKEY_PTR, _ENGINE_PTR, mkcgo_err_state *);
_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new_from_pkey(_OSSL_LIB_CTX_PTR, _EVP_PKEY_PTR, const char*, mkcgo_err_state *);
_EVP_PKEY_CTX_PTR _mkcgo_EVP_PKEY_CTX_new_id(int, _ENGINE_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_set0_rsa_oaep_label(_EVP_PKEY_CTX_PTR, void*, int, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_set1_hkdf_key(_EVP_PKEY_CTX_PTR, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_set1_hkdf_salt(_EVP_PKEY_CTX_PTR, const unsigned char*, int, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_set_hkdf_md(_EVP_PKEY_CTX_PTR, const _EVP_MD_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_CTX_set_hkdf_mode(_EVP_PKEY_CTX_PTR, int, mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_EC(_OSSL_LIB_CTX_PTR, const char*, const char*, const char*, mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_ED25519(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_Q_keygen_RSA(_OSSL_LIB_CTX_PTR, const char*, const char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_assign(_EVP_PKEY_PTR, int, void*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_decrypt(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_decrypt_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_derive(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_derive_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_derive_set_peer(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_encrypt(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_encrypt_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
void _mkcgo_EVP_PKEY_free(_EVP_PKEY_PTR);
int _mkcgo_EVP_PKEY_fromdata(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, int, _OSSL_PARAM_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_fromdata_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
_DSA_PTR _mkcgo_EVP_PKEY_get0_DSA(_EVP_PKEY_PTR, mkcgo_err_state *);
_EC_KEY_PTR _mkcgo_EVP_PKEY_get0_EC_KEY(_EVP_PKEY_PTR, mkcgo_err_state *);
_RSA_PTR _mkcgo_EVP_PKEY_get1_RSA(_EVP_PKEY_PTR, mkcgo_err_state *);
size_t _mkcgo_EVP_PKEY_get1_encoded_public_key(_EVP_PKEY_PTR, unsigned char**, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_get_bits(const _EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_get_bn_param(const _EVP_PKEY_PTR, const char*, _BIGNUM_PTR*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_get_raw_private_key(const _EVP_PKEY_PTR, unsigned char*, size_t*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_get_raw_public_key(const _EVP_PKEY_PTR, unsigned char*, size_t*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_get_size(const _EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_keygen(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_keygen_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new(mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new_raw_private_key(int, _ENGINE_PTR, const unsigned char*, size_t, mkcgo_err_state *);
_EVP_PKEY_PTR _mkcgo_EVP_PKEY_new_raw_public_key(int, _ENGINE_PTR, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_paramgen(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_paramgen_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_private_check(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_public_check_quick(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_set1_EC_KEY(_EVP_PKEY_PTR, _EC_KEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_set1_encoded_public_key(_EVP_PKEY_PTR, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_sign(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_sign_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_up_ref(_EVP_PKEY_PTR, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_verify(_EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t, mkcgo_err_state *);
int _mkcgo_EVP_PKEY_verify_init(_EVP_PKEY_CTX_PTR, mkcgo_err_state *);
_EVP_SIGNATURE_PTR _mkcgo_EVP_SIGNATURE_fetch(_OSSL_LIB_CTX_PTR, const char*, const char*, mkcgo_err_state *);
void _mkcgo_EVP_SIGNATURE_free(_EVP_SIGNATURE_PTR);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_cbc(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_ctr(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_ecb(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_128_gcm(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_cbc(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_ctr(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_ecb(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_192_gcm(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_cbc(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_ctr(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_ecb(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_aes_256_gcm(void);
int _mkcgo_EVP_default_properties_enable_fips(_OSSL_LIB_CTX_PTR, int, mkcgo_err_state *);
int _mkcgo_EVP_default_properties_is_fips_enabled(_OSSL_LIB_CTX_PTR);
const _EVP_CIPHER_PTR _mkcgo_EVP_des_cbc(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_des_ecb(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_des_ede3_cbc(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_des_ede3_ecb(void);
const _EVP_MD_PTR _mkcgo_EVP_md4(void);
const _EVP_MD_PTR _mkcgo_EVP_md5(void);
const _EVP_MD_PTR _mkcgo_EVP_md5_sha1(void);
const _EVP_CIPHER_PTR _mkcgo_EVP_rc4(void);
const _EVP_MD_PTR _mkcgo_EVP_ripemd160(void);
const _EVP_MD_PTR _mkcgo_EVP_sha1(void);
const _EVP_MD_PTR _mkcgo_EVP_sha224(void);
const _EVP_MD_PTR _mkcgo_EVP_sha256(void);
const _EVP_MD_PTR _mkcgo_EVP_sha384(void);
const _EVP_MD_PTR _mkcgo_EVP_sha3_224(void);
const _EVP_MD_PTR _mkcgo_EVP_sha3_256(void);
const _EVP_MD_PTR _mkcgo_EVP_sha3_384(void);
const _EVP_MD_PTR _mkcgo_EVP_sha3_512(void);
const _EVP_MD_PTR _mkcgo_EVP_sha512(void);
const _EVP_MD_PTR _mkcgo_EVP_sha512_224(void);
const _EVP_MD_PTR _mkcgo_EVP_sha512_256(void);
int _mkcgo_FIPS_mode(void);
int _mkcgo_FIPS_mode_set(int, mkcgo_err_state *);
int _mkcgo_HMAC_CTX_copy(_HMAC_CTX_PTR, _HMAC_CTX_PTR, mkcgo_err_state *);
void _mkcgo_HMAC_CTX_free(_HMAC_CTX_PTR);
_HMAC_CTX_PTR _mkcgo_HMAC_CTX_new(mkcgo_err_state *);
int _mkcgo_HMAC_Final(_HMAC_CTX_PTR, unsigned char*, unsigned int*, mkcgo_err_state *);
int _mkcgo_HMAC_Init_ex(_HMAC_CTX_PTR, const void*, int, const _EVP_MD_PTR, _ENGINE_PTR, mkcgo_err_state *);
int _mkcgo_HMAC_Update(_HMAC_CTX_PTR, const unsigned char*, size_t, mkcgo_err_state *);
const char* _mkcgo_OBJ_nid2sn(int);
void _mkcgo_OPENSSL_init(void);
int _mkcgo_OPENSSL_init_crypto(uint64_t, const _OPENSSL_INIT_SETTINGS_PTR, mkcgo_err_state *);
unsigned int _mkcgo_OPENSSL_version_major(void);
unsigned int _mkcgo_OPENSSL_version_minor(void);
unsigned int _mkcgo_OPENSSL_version_patch(void);
void _mkcgo_OSSL_PARAM_BLD_free(_OSSL_PARAM_BLD_PTR);
_OSSL_PARAM_BLD_PTR _mkcgo_OSSL_PARAM_BLD_new(mkcgo_err_state *);
int _mkcgo_OSSL_PARAM_BLD_push_BN(_OSSL_PARAM_BLD_PTR, const char*, const _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_OSSL_PARAM_BLD_push_int32(_OSSL_PARAM_BLD_PTR, const char*, int32_t, mkcgo_err_state *);
int _mkcgo_OSSL_PARAM_BLD_push_octet_string(_OSSL_PARAM_BLD_PTR, const char*, const void*, size_t, mkcgo_err_state *);
int _mkcgo_OSSL_PARAM_BLD_push_utf8_string(_OSSL_PARAM_BLD_PTR, const char*, const char*, size_t, mkcgo_err_state *);
_OSSL_PARAM_PTR _mkcgo_OSSL_PARAM_BLD_to_param(_OSSL_PARAM_BLD_PTR, mkcgo_err_state *);
void _mkcgo_OSSL_PARAM_free(_OSSL_PARAM_PTR);
const _OSSL_PARAM_PTR _mkcgo_OSSL_PARAM_locate_const(const _OSSL_PARAM_PTR, const char*, mkcgo_err_state *);
int _mkcgo_OSSL_PROVIDER_available(_OSSL_LIB_CTX_PTR, const char*);
const char* _mkcgo_OSSL_PROVIDER_get0_name(const _OSSL_PROVIDER_PTR);
_OSSL_PROVIDER_PTR _mkcgo_OSSL_PROVIDER_try_load(_OSSL_LIB_CTX_PTR, const char*, int, mkcgo_err_state *);
const char* _mkcgo_OpenSSL_version(int);
unsigned long _mkcgo_OpenSSL_version_num(void);
int _mkcgo_PKCS5_PBKDF2_HMAC(const char*, int, const unsigned char*, int, int, const _EVP_MD_PTR, int, unsigned char*, mkcgo_err_state *);
int _mkcgo_RAND_bytes(unsigned char*, int, mkcgo_err_state *);
void _mkcgo_RSA_free(_RSA_PTR);
void _mkcgo_RSA_get0_crt_params(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void _mkcgo_RSA_get0_factors(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void _mkcgo_RSA_get0_key(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_RSA_PTR _mkcgo_RSA_new(mkcgo_err_state *);
int _mkcgo_RSA_set0_crt_params(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_RSA_set0_factors(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);
int _mkcgo_RSA_set0_key(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR, mkcgo_err_state *);

#endif // MKCGO_H
