// Code generated by mkcgo. DO NOT EDIT.

//go:build go1.24 && !cmd_go_bootstrap

package ossl

/*
#cgo noescape _mkcgo_EVP_CipherUpdate
#cgo nocallback _mkcgo_EVP_CipherUpdate
#cgo noescape _mkcgo_EVP_DecryptFinal_ex
#cgo nocallback _mkcgo_EVP_DecryptFinal_ex
#cgo noescape _mkcgo_EVP_DecryptUpdate
#cgo nocallback _mkcgo_EVP_DecryptUpdate
#cgo noescape _mkcgo_EVP_Digest
#cgo nocallback _mkcgo_EVP_Digest
#cgo noescape _mkcgo_EVP_DigestFinal_ex
#cgo nocallback _mkcgo_EVP_DigestFinal_ex
#cgo noescape _mkcgo_EVP_DigestSign
#cgo nocallback _mkcgo_EVP_DigestSign
#cgo noescape _mkcgo_EVP_DigestUpdate
#cgo nocallback _mkcgo_EVP_DigestUpdate
#cgo noescape _mkcgo_EVP_EncryptFinal_ex
#cgo nocallback _mkcgo_EVP_EncryptFinal_ex
#cgo noescape _mkcgo_EVP_EncryptUpdate
#cgo nocallback _mkcgo_EVP_EncryptUpdate
#cgo noescape _mkcgo_EVP_MD_CTX_copy
#cgo nocallback _mkcgo_EVP_MD_CTX_copy
#cgo noescape _mkcgo_EVP_PKEY_derive
#cgo nocallback _mkcgo_EVP_PKEY_derive
#cgo noescape _mkcgo_EVP_PKEY_get_raw_private_key
#cgo nocallback _mkcgo_EVP_PKEY_get_raw_private_key
#cgo noescape _mkcgo_EVP_PKEY_get_raw_public_key
#cgo nocallback _mkcgo_EVP_PKEY_get_raw_public_key
#cgo noescape _mkcgo_RAND_bytes
#cgo nocallback _mkcgo_RAND_bytes
*/
import "C"
