# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This template expands a list of builders into a list of jobs.

parameters:
  # [] of { id, os, arch, hostarch, config, distro?, experiment? }
  builders: []
  # If true, publish build artifacts to blob storage.
  publish: false
  # If changed to specify an existing pipeline run, skip build/sign and publish the existing run.
  publishExistingRunID: 'nil'
  # If true, include a signing stage+job that depends on all 'buildandpack' builder jobs finishing.
  # 'official' is passed through into run-stage.yml, where it has other effects.
  official: false
  # If true, generate source archive tarballs.
  createSourceArchive: false
  # If true, generate and publish symbols (aka PDBs).
  createSymbols: false
  releaseVersion: 'nil'

stages:
  - ${{ if eq(parameters.publishExistingRunID, 'nil') }}:
    - ${{ each builder in parameters.builders }}:
      - template: pool.yml
        parameters:
          inner:
            template: run-stage.yml
            parameters:
              builder: ${{ builder }}
              createSourceArchive: ${{ parameters.createSourceArchive }}
              releaseVersion: ${{ parameters.releaseVersion }}
              official: ${{ parameters.official }}
              createSymbols: ${{ parameters.createSymbols }}
              # Attempt to retry the build on Windows to mitigate flakiness:
              # "Access Denied" during EXE copying and general flakiness during tests.
              ${{ if eq(builder.os, 'windows') }}:
                retryAttempts: [1, 2, 3, 4, "FINAL"]

    - ${{ if eq(parameters.official, true) }}:
      - template: pool.yml
        parameters:
          inner:
            template: sign-stage.yml
            parameters:
              # This is not a builder, but provide partial builder info for agent selection.
              builder: { os: windows, arch: amd64 }
              official: ${{ parameters.official }}
              # The list of builders to depend on and grab artifacts from.
              builders:
                - ${{ each builder in parameters.builders }}:
                  - ${{ if eq(builder.config, 'buildandpack') }}:
                    - ${{ builder }}

  - ${{ if eq(parameters.publish, true) }}:
    - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/internal/')) }}:
      - template: pool.yml
        parameters:
          inner:
            template: publish-stage.yml
            parameters:
              # This is not a builder, but provide partial builder info for agent selection.
              builder: { os: windows, arch: amd64 }
              official: true
              public: true
              publishExistingRunID: ${{ parameters.publishExistingRunID }}

    - template: pool.yml
      parameters:
        inner:
          template: publish-stage.yml
          parameters:
            builder: { os: windows, arch: amd64 }
            official: true
            public: false
            builders:
              - ${{ each builder in parameters.builders }}:
                - ${{ if eq(builder.config, 'buildandpack') }}:
                  - ${{ builder }}
            publishSymbols: ${{ parameters.createSymbols }}
            publishExistingRunID: ${{ parameters.publishExistingRunID }}
