# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This template determines the correct pool names and agent demands based on the current branch and
# AzDO project and passes them into the provided inner stages template.
#
# The "public" (vs. internal) and "servicing" (vs. R&D) conditions are evaluated here and then
# passed into an inner template so the values can be reused to determine the pools to use.
#
# See pool-core.yml for the list of pool names and demands and the reasons behind the choices.

parameters:
  # The inner template: { template string, parameters object }
  # Note: the template path is relative to this file (inside "stages/"), not the caller's file path.
  - name: inner
    type: object

stages:
  - template: pool-core.yml
    parameters:
      public: ${{ eq(variables['System.TeamProject'], 'public') }}
      servicing: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/microsoft/release-branch') }}
      inner: ${{ parameters.inner }}
