# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This template defines common pool names for dnceng agents for various platforms.

parameters:
  - name: public
    type: boolean
  - name: servicing
    type: boolean
  # The inner template: { template string, parameters object }
  - name: inner
    type: object

stages:
  - template: ${{ parameters.inner.template }}
    parameters:
      ${{ insert }}: ${{ parameters.inner.parameters }}

      dncengPool:
        # Pick pool. https://github.com/dotnet/arcade/blob/0db07252ccb18afdf94820ba6125da6de729ec04/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#agent-queues
        ${{ if parameters.public }}:
          ${{ if parameters.servicing }}:
            name: NetCore-Svc-Public
          ${{ else }}:
            name: NetCore-Public
        ${{ else }}:
          ${{ if parameters.servicing }}:
            name: NetCore1ESPool-Svc-Internal
          ${{ else }}:
            name: NetCore1ESPool-Internal

        # Pick images. https://helix.dot.net/#1esPools
        demands:
          ${{ if parameters.public }}:
            windows: ImageOverride -equals 1es-windows-2022-open
          ${{ else }}:
            windows: ImageOverride -equals 1es-windows-2022

          ${{ if parameters.public }}:
            linux: ImageOverride -equals 1es-ubuntu-2004-open
          ${{ else }}:
            linux: ImageOverride -equals 1es-ubuntu-2004
