# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

parameters:
  - name: inner
    type: object

  - name: public
    type: boolean
  - name: servicing
    type: boolean
  - name: official
    type: boolean
  - name: os
    type: string
  - name: hostArch
    type: string

stages:
  - template: pool-2.yml
    parameters:
      ${{ insert }}: ${{ parameters }}

      ${{ if eq(parameters.os, 'darwin') }}:
        name: Azure Pipelines # use the default AzDo hosted pool
      ${{ elseif and(eq(parameters.hostArch, 'arm64'), eq(parameters.os, 'linux')) }}:
        name: Docker-Linux-Arm-Internal
      ${{ else }}:
        ${{ if parameters.public }}:
          # https://github.com/dotnet/arcade/blob/0db07252ccb18afdf94820ba6125da6de729ec04/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#agent-queues
          ${{ if parameters.servicing }}:
            name: NetCore-Svc-Public
          ${{ else }}:
            name: NetCore-Public
        ${{ else }}:
          ${{ if parameters.servicing }}:
            name: netcore1espool-svc-internal
          ${{ else }}:
            name: netcore1espool-internal
