# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This stage performs common setup for each of the several stages involved in
# public publishing using Release Studio. It gets the utilities needed to
# publish the build artifacts publicly, executes common logic needed by each
# stage involved, and then executes some provided steps.

parameters:
  - name: ctx
    type: object

  - name: pool
    type: object

  - name: id 
    type: string

  - name: dependsOn
    type: object
    default: []

  - name: templateContext
    type: object
    default: {}

  - name: variables
    type: object
    default: []

  - name: steps
    type: object

stages:
  - stage: ${{ parameters.id }}
    dependsOn: ${{ parameters.dependsOn }}

    jobs:
      - job: ${{ parameters.id }}
        pool: ${{ parameters.pool }}
        workspace:
          clean: all
        timeoutInMinutes: 240 # 4hr
        ${{ if parameters.templateContext }}:
          templateContext: ${{ parameters.templateContext }}
        variables:
          # Group includes these relevant variables:
          # - ReleaseStudioPublishOwnerAliases
          - group: go-release-config

          # This is read directly by release studio scripts through env.
          - name: RMExecutionEnvironment
            value: Production

          - name: GoBinariesDir
            value: $(Pipeline.Workspace)/Binaries Signed

          - name: NetCorePublishingScriptsPackages
            value: $(Build.SourcesDirectory)/eng/artifacts/MsGoPublishingScripts/Packages

          - ${{ each variable in parameters.variables }}:
            - ${{ variable }}
        steps:
          - template: ../steps/checkout-windows-task.yml
          - template: ../steps/find-PublishBranchAlias-task.yml

          # Install the latest version of the publish tools package. The
          # floating dependency is recommended by the RM team to allow them to
          # make updates to the system. UI to fetch the package as a dev is at:
          # https://dev.azure.com/dnceng/internal/_artifacts/feed/MicroBuildToolset/NuGet/DevDiv.RM.MS.Go.Publishing
          - task: NuGetCommand@2
            displayName: NuGet install RM Tools Package
            inputs:
              command: custom
              feedRestore: MicroBuildToolset
              arguments: >-
                install DevDiv.RM.MS.Go.Publishing
                -Source https://pkgs.dev.azure.com/dnceng/_packaging/MicroBuildToolset/nuget/v3/index.json
                -OutputDirectory $(NetCorePublishingScriptsPackages)
                -Verbosity Detailed

          - pwsh: |
              $packageDir = Get-ChildItem `
                -Path $(NetCorePublishingScriptsPackages) `
                -Filter "DevDiv.RM.MS.Go.Publishing*" `
                -Directory

              Write-Host "Tools package dir: $packageDir"
              if ($packageDir.Count -ne 1) {
                throw "Expected exactly one publishing tools package installed, found $($packageDir.Count)."
              }

              Write-Output "##vso[task.setvariable variable=NetCorePublishingScripts]$packageDir\scripts"
            displayName: Find RM Tools scripts directory

          - ${{ each step in parameters.steps }}:
            - ${{ step }}
