trigger:
  batch: true
  branches:
    include:
      - microsoft/docker-images
pr: none

variables:
  - template: variables/common.yml

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
