trigger: none
pr:
  branches:
    include:
      - microsoft/docker-images

variables:
  - template: variables/common.yml

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
