# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline can be triggered via PR comment to run outerloop builders.

trigger: none
pr:
  # Configure this pipeline to *potentially* run on any Microsoft-maintained branch. The pattern
  # allows commands like "/azp run" to find this pipeline.
  #
  # Note: if all we did was configure "pr:", this pipeline would be triggered *by default* on any
  # new PR. To make the pipeline run on demand, the pipeline definition must be adjusted using the
  # AzDO UI to require a comment before running the build. There is unfortunately no way to
  # configure this from YAML.
  - microsoft/*
  - dev/*

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      outerloop: true
