# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline can be triggered via PR comment to run outerloop builders.

# https://dev.azure.com/dnceng-public/public/_build?definitionId=192

trigger: none
pr:
  # Configure this pipeline to *potentially* run on any Microsoft-maintained branch. The pattern
  # allows commands like "/azp run" to find this pipeline.
  #
  # Note: if all we did was configure "pr:", this pipeline would be triggered *by default* on any
  # new PR. To make the pipeline run on demand, the pipeline definition must be adjusted using the
  # AzDO UI to require a comment before running the build. There is unfortunately no way to
  # configure this from YAML.
  - microsoft/*
  - dev/*

variables:
  - template: variables/pipeline.yml

resources:
  containers:
    - container: ubuntu2204
      image: mcr.microsoft.com/microsoft-go/infra-images:ubuntu-22.04-amd64-default
    - container: mariner2
      image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-amd64-default
    - container: mariner2arm64
      image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-arm64-default
    - container: azurelinux3
      image: mcr.microsoft.com/microsoft-go/infra-images:azurelinux-3.0-amd64-default

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      ctx: {}
      outerloop: true
