# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline validates PRs. It builds Go and runs inner loop tests.

trigger: none
pr:
  - microsoft/*
  - dev/*

variables:
  - template: variables/pipeline.yml

resources:
  containers:
    # Predefine named containers. Using "container:" inside the job would work, because this is not
    # 1ES PT. However, to share code, use the same names here. Unfortunately the format used here
    # (container: ... image: ...) is not the same as the one 1ES PT uses, so updating these requires
    # separate changes.
    - container: ubuntu2204
      image: mcr.microsoft.com/microsoft-go/infra-images:ubuntu-22.04-amd64-default-20241026145220-02e8663
    - container: mariner2
      image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-amd64-default-20241029143752-6049f85
    - container: mariner2arm64
      image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-arm64-default-20241029143304-6049f85
    - container: azurelinux3
      image: mcr.microsoft.com/microsoft-go/infra-images:azurelinux-3.0-amd64-default-20241210101540-a3a1203

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      ctx: {}
      innerloop: true
      buildandpack: true
