# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline validates PRs. It builds Go and runs inner loop tests.

trigger: none
pr:
  - microsoft/*
  - dev/*

resources:
  containers:
    # Predefine named containers. Using "container:" inside the job would work, because this is not
    # 1ES PT. However, to share code, use the same names here. Unfortunately the format used here
    # (container: ... image: ...) is not the same as the one 1ES PT uses, so updating these requires
    # separate changes.
    - container: ubuntu2204
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04
    - container: mariner1
      image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-1.0.20211027-20211201-0cccc22
    - container: mariner1arm64
      image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-arm64-1.0-20220314-a003148

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      innerloop: true
      buildandpack: true
