# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# official: https://dev.azure.com/dnceng/internal/_build?definitionId=958
# unofficial: https://dev.azure.com/dnceng/internal/_build?definitionId=1485

pipelineymlgen:
  output:
    - file: rolling-internal-pipeline.yml
---

trigger:
  # We need a build to automatically trigger on each release branch commit as
  # quickly as possible. According to the AzDO pipeline schema, there is no way
  # to configure the non-batching trigger to only apply to certain branches.
  batch: false
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - ${ inlinetemplate "util/info.gen.yml" }:
      desc: This pipeline builds, signs, and publishes the Microsoft build of Go. It runs internally and may publish release artifacts.

  - name: releaseVersion
    displayName: '[Release automation input] The version being built. Leave "nil" for non-release builds.'
    type: string
    default: nil

  - name: publishReleaseStudio
    displayName: >
      For debugging publish steps: force publishing artifacts to the public
      using Release Studio integration, even if this isn't the official pipeline
      or this isn't a release branch.
    type: boolean
    default: false

  - name: publishExistingRunID
    displayName: 'For debugging publish steps: skip building, and instead publish the artifacts from an existing run. Leave "nil" otherwise.'
    type: string
    default: nil

  - name: signExistingRunID
    displayName: 'For debugging signing: skip building, and instead sign the artifacts from an existing run. Leave "nil" otherwise.'
    type: string
    default: 'nil'

variables:
  - template: variables/pipeline.yml
  - template: variables/pool-providers.yml

  # MicroBuild configuration.
  - name: TeamName
    value: golang

  - name: GoSigningType # Note: not quite SignType. MicroBuild generates SignType.
    ${{ if variables['Go1ESOfficial'] }}:
      value: 'real'
    ${{ else }}:
      value: 'test'

  # Publish buildandpack artifacts to pipeline using 1ES PT.
  - name: GoPublishArtifacts
    value: 'true'

  - name: GoPublishReleaseStudio
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/internal/') }}:
      value: '' # Never publish internal branches using release studio, even if checkbox ticked.
    ${{ elseif parameters.publishReleaseStudio }}:
      value: 'true'
    # We've dealt with manual opt-in. Next, determine the default behavior:
    ${{ elseif and(variables['Go1ESOfficial'], startsWith(variables['Build.SourceBranch'], 'refs/heads/microsoft/release-branch.go')) }}:
      value: 'true' # Publish a release branch built in the official pipeline by default.
    ${{ else }}:
      value: ''

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  ${{ if variables['Go1ESOfficial'] }}:
    template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  ${{ else }}:
    template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    pool:
      # Default, used for SDL analysis.
      name: $(DncEngInternalBuildPool)
      image: 1es-windows-2022
      os: windows
    featureFlags:
      # https://github.com/microsoft/go-lab/issues/288
      useOptimizedSDLTasks: false
    sdl:
      enableProductionSDL: true
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'Scan runs in validation pipeline.'
      componentgovernance:
        # Stage 0 is a temporary bootstrap toolchain and is not shipped.
        ignoreDirectories: '$(Build.SourcesDirectory)/eng/artifacts/_goStage0'
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json

    stages:
      - template: stages/go-builder-matrix-stages.yml
        parameters:
          # There is a limitation with compile-time references to user-defined
          # variables: each stages template actually has its own "variables" map
          # and doesn't inherit global variables other than default ones. Values
          # that can be used in this file like "variables['Go1ESOfficial']" must
          # be passed along manually for compile-time use like
          # "parameters.ctx['Go1ESOfficial']" by templates. This limitation is not
          # documented as of writing.
          #
          # Only pass "Go*" variables to avoid built-in variables. There are a
          # lot, and they clutter attempts to debug pipeline behavior.
          ctx:
            ${{ each variable in variables }}:
              ${{ if startsWith(variable.key, 'Go') }}:
                ${{ variable.key }}: ${{ variable.value }}
          buildandpack: true
          sign: true
          signExistingRunID: ${{ parameters.signExistingRunID }}
          createSourceArchive: true
          createSymbols: true
          publish: true
          publishExistingRunID: ${{ parameters.publishExistingRunID }}
          releaseVersion: ${{ parameters.releaseVersion }}