# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling validation, like CodeQL.

# official: https://dev.azure.com/dnceng/internal/_build?definitionId=1354

trigger: none
pr: none

variables:
  - template: variables/pipeline.yml
  - template: variables/codeql.yml
  - template: variables/pool-providers.yml

resources:
  pipelines:
    - pipeline: build
      # The rolling pipeline and this validation pipeline share the same source repository. AzDO
      # sees this and makes this pipeline's "checkout" steps download the same source code that was
      # built by the microsoft-go pipeline:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-pipelines-resource
      #
      # This means we can have SDL scan the currently-checked-out source code as the way to scan the
      # source code of the internal rolling build.
      source: microsoft-go
      # Trigger can't be conditioned, so this resource can't be declared inside
      # the template. "A template expression is not allowed in this context".
      trigger:
        branches:
          include:
            - microsoft/main
            - microsoft/release-branch.*

extends:
  template: rolling-internal-validation.yml
  parameters:
    ctx:
      ${{ each variable in variables }}:
        ${{ if startsWith(variable.key, 'Go') }}:
          ${{ variable.key }}: ${{ variable.value }}
