# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs innerloop (reliable, relatively quick) tests on rolling builds.
# The intent is that if this pipeline fails, it should block official release for a good reason.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

parameters:
  # By default, don't use the shared, potentially constrained linux-arm64 pool.
  - name: includeArm64Host
    displayName: 'Include Linux arm64 host builders'
    type: boolean
    default: false

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
    containers:
      ubuntu2204:
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04
      mariner1:
        image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-1.0.20211027-20211201-0cccc22
      mariner1arm64:
        image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-arm64-1.0-20220314-a003148

    stages:
      - template: stages/go-builder-matrix-stages.yml
        parameters:
          innerloop: true
          # Include buildandpack builders. The official internal build uses slightly different build
          # machines than this pipeline. This one tests against our minimum requirements.
          buildandpack: true
          includeArm64Host: ${{ parameters.includeArm64Host }}
