# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling builders that include tests that may be unreliable or very slow.
# If a test is reliable/fast, it should be run by rolling-innerloop-pipeline.yml.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      outerloop: true
