# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling validation, like CodeQL.

# unofficial: https://dev.azure.com/dnceng/internal/_build?definitionId=1486

trigger: none
pr: none

variables:
  - template: variables/pipeline.yml
  - template: variables/codeql.yml
  - template: variables/pool-providers.yml

  # The default cadence is ok for official branches. The cadence is per-branch.
  # For a dev build, the cadence would prevent dev iteration.
  # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-general-faq#how-do-i-check-if-my-project-is-onboarded
  - name: Codeql.Cadence
    value: 0

resources:
  pipelines:
    - pipeline: build
      source: microsoft-go

extends:
  template: rolling-internal-validation.yml
  parameters:
    ctx:
      ${{ each variable in variables }}:
        ${{ if startsWith(variable.key, 'Go') }}:
          ${{ variable.key }}: ${{ variable.value }}
