# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs innerloop (reliable, relatively quick) tests on rolling builds.
# The intent is that if this pipeline fails, it should block official release for a good reason.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

parameters:
  # By default, don't use the shared, potentially constrained linux-arm64 pool.
  - name: includeArm64Host
    displayName: 'Include Linux arm64 host builders'
    type: boolean
    default: false

variables:
  MS_GOTOOLCHAIN_TELEMETRY_ENABLED: '0'

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
    containers:
      ubuntu2204:
        image: mcr.microsoft.com/microsoft-go/infra-images:ubuntu-22.04-amd64-default-20241026145220-02e8663
      mariner2:
        image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-amd64-default-20241029143752-6049f85
      mariner2arm64:
        image: mcr.microsoft.com/microsoft-go/infra-images:cbl-mariner-2.0-arm64-default-20241029143304-6049f85
      azurelinux3:
        image: mcr.microsoft.com/microsoft-go/infra-images:azurelinux-3.0-amd64-default-20241210101540-a3a1203

    stages:
      - template: stages/go-builder-matrix-stages.yml
        parameters:
          innerloop: true
          # Include buildandpack builders. The official internal build uses slightly different build
          # machines than this pipeline. This one tests against our minimum requirements.
          buildandpack: true
          includeArm64Host: ${{ parameters.includeArm64Host }}
