# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline builds Go, runs inner loop tests, signs the packages, and publishes. It only runs
# internally, via commit trigger.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - name: releaseVersion
    displayName: '[Release automation input] The version being built. Leave "nil" for non-release builds.'
    type: string
    default: nil

  - name: publishExistingRunID
    displayName: 'For debugging publish steps: skip building, and instead publish the artifacts from an existing run. Leave "nil" otherwise.'
    type: string
    default: nil

variables:
  - template: variables/pool-providers.yml
  # MicroBuild configuration.
  - name: TeamName
    value: golang

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      # Default, used for SDL analysis.
      name: $(DncEngInternalBuildPool)
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'Scan runs in validation pipeline.'
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json

    stages:
      - template: stages/go-builder-matrix-stages.yml
        parameters:
          buildandpack: true
          official: true
          sign: true
          createSourceArchive: true
          createSymbols: true
          publish: true
          publishExistingRunID: ${{ parameters.publishExistingRunID }}
          releaseVersion: ${{ parameters.releaseVersion }}
