# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling builders that include tests that may be unreliable or very slow.
# If a test is reliable/fast, it should be run by rolling-innerloop-pipeline.yml.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
    containers:
      ubuntu1804:
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20211022152710-047508b
      mariner1:
        image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-1.0.20211027-20211201-0cccc22
      mariner1arm64:
        image: golangpublicimages.azurecr.io/go-infra-images/prereqs:cbl-mariner-arm64-1.0-20220314-a003148

    stages:
      - template: stages/go-builder-matrix-stages.yml
        parameters:
          outerloop: true
