# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs innerloop (reliable, relatively quick) tests on rolling builds.
# The intent is that if this pipeline fails, it should block official release for a good reason.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

parameters:
  # By default, don't use the shared, potentially constrained linux-arm64 pool.
  - name: includeArm64Host
    displayName: 'Include Linux arm64 host builders'
    type: boolean
    default: false

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      innerloop: true
      # Include buildandpack builders. The official internal build uses slightly different build
      # machines than this pipeline. This one tests against our minimum requirements.
      buildandpack: true
      includeArm64Host: ${{ parameters.includeArm64Host }}
