# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling builds. This includes inner+outerloop to make sure we have complete
# coverage on each commit that we build.
#
# If we relied on the publish pipeline to run innerloop, commit coverage could be spotty due to
# batching and the long outerloop run time. Also, the publish pipeline is internal, so it would make
# it harder to find results vs. public outerloop runs.

trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

stages:
  - template: stages/go-builder-matrix-stages.yml
    parameters:
      innerloop: true
      outerloop: true
