// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

package sha512

import (
	"hash"

	"github.com/microsoft/go/cryptobackend"
)

type hashAlgorithm uint8

const (
	hashSHA512 hashAlgorithm = iota
	hashSHA384
	hashSHA512_224
	hashSHA512_256
)

// Hash dispatches hash operations to a native or fallback implementation.
// Its zero value selects hashSHA512.
type Hash struct {
	fips        fipsHash
	backend     *backendHash
	algorithm   hashAlgorithm
	initialized bool
}

func newHash(algorithm hashAlgorithm) *Hash {
	return &Hash{algorithm: algorithm}
}

func (h *Hash) init() {
	if h.initialized {
		return
	}
	h.initialized = true
	switch h.algorithm {
	case hashSHA512:
		if backend.Enabled && Supports512() {
			h.backend = newBackendHash512()
			return
		}
		h.fips = *initFallback512()
	case hashSHA384:
		if backend.Enabled && Supports384() {
			h.backend = newBackendHash384()
			return
		}
		h.fips = *initFallback384()
	case hashSHA512_224:
		if backend.Enabled && Supports512_224() {
			h.backend = newBackendHash512_224()
			return
		}
		h.fips = *initFallback512_224()
	case hashSHA512_256:
		if backend.Enabled && Supports512_256() {
			h.backend = newBackendHash512_256()
			return
		}
		h.fips = *initFallback512_256()
	default:
		panic("cryptobackend: invalid hash algorithm")
	}
}

func (h *Hash) Write(p []byte) (int, error) {
	h.init()
	if h.backend != nil {
		return h.backend.Write(p)
	}
	return h.fips.Write(p)
}

func (h *Hash) Sum(p []byte) []byte {
	h.init()
	if h.backend != nil {
		return h.backend.Sum(p)
	}
	return h.fips.Sum(p)
}

func (h *Hash) Reset() {
	h.init()
	if h.backend != nil {
		h.backend.Reset()
		return
	}
	h.fips.Reset()
}

func (h *Hash) Size() int {
	h.init()
	if h.backend != nil {
		return h.backend.Size()
	}
	return h.fips.Size()
}

func (h *Hash) BlockSize() int {
	h.init()
	if h.backend != nil {
		return h.backend.BlockSize()
	}
	return h.fips.BlockSize()
}

func (h *Hash) MarshalBinary() ([]byte, error) {
	h.init()
	if h.backend != nil {
		return h.backend.MarshalBinary()
	}
	return h.fips.MarshalBinary()
}

func (h *Hash) AppendBinary(p []byte) ([]byte, error) {
	h.init()
	if h.backend != nil {
		return h.backend.AppendBinary(p)
	}
	return h.fips.AppendBinary(p)
}

func (h *Hash) UnmarshalBinary(data []byte) error {
	h.init()
	if h.backend != nil {
		return h.backend.UnmarshalBinary(data)
	}
	return h.fips.UnmarshalBinary(data)
}

func (h *Hash) Clone() (hash.Cloner, error) {
	r := *h
	r.init()
	if r.backend != nil {
		cloned, err := r.backend.Clone()
		if err != nil {
			return nil, err
		}
		r.backend = cloned.(*backendHash)
	}
	return &r, nil
}

func (h *Hash) unwrap() hash.Hash {
	h.init()
	if h.backend != nil {
		return h.backend
	}
	return &h.fips
}
