// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build msgostd || cmd_go_bootstrap

package sha512

import (
	fallback "crypto/internal/fips140/sha512"
	"hash"
)

type fipsHash = fallback.Digest

func initFallback512() *fipsHash { return fallback.New() }

func initFallback384() *fipsHash { return fallback.New384() }

func initFallback512_224() *fipsHash { return fallback.New512_224() }

func initFallback512_256() *fipsHash { return fallback.New512_256() }

func New() *Hash { return newHash(hashSHA512) }

func New384() *Hash { return newHash(hashSHA384) }

func New512_224() *Hash { return newHash(hashSHA512_224) }

func New512_256() *Hash { return newHash(hashSHA512_256) }

// Unwrap returns the selected hash implementation.
func Unwrap(h *Hash) hash.Hash { return h.unwrap() }
