# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- microsoft/*
pr:
- microsoft/*

jobs:
- job: Build
  pool:
    # The VM image of the Docker host. This doesn't need to match the container image, but it may
    # give slightly better coverage by matching the kernel version.
    vmImage: ubuntu-18.04
  # The image used for the container this job runs in.
  container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20210223192210-047508b
  workspace:
    clean: all
  steps:
  - template: pipeline/checkout-unix-task.yml

  - script: |
      set -ex
      microsoft/build.sh --test
    displayName: Build and Test

  - script: |
      set -ex
      microsoft/pack.sh
    displayName: Pack

  - publish: microsoft/artifacts
    artifact: Binaries
    displayName: Pipeline publish
    condition: succeededOrFailed()
