// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build !msgostd && !cmd_go_bootstrap

package sha3

import "hash"

type fipsHash struct{}

func (*fipsHash) Write([]byte) (int, error)      { panic("cryptobackend: not available") }
func (*fipsHash) Sum([]byte) []byte              { panic("cryptobackend: not available") }
func (*fipsHash) Reset()                         { panic("cryptobackend: not available") }
func (*fipsHash) Size() int                      { panic("cryptobackend: not available") }
func (*fipsHash) BlockSize() int                 { panic("cryptobackend: not available") }
func (*fipsHash) MarshalBinary() ([]byte, error) { panic("cryptobackend: not available") }
func (*fipsHash) AppendBinary([]byte) ([]byte, error) {
	panic("cryptobackend: not available")
}
func (*fipsHash) UnmarshalBinary([]byte) error { panic("cryptobackend: not available") }
func (*fipsHash) Clone() (hash.Cloner, error)  { panic("cryptobackend: not available") }

func initFallback256() *fipsHash { panic("cryptobackend: not available") }

func initFallback224() *fipsHash { panic("cryptobackend: not available") }

func initFallback384() *fipsHash { panic("cryptobackend: not available") }

func initFallback512() *fipsHash { panic("cryptobackend: not available") }

func New256() *Hash { return newHash(hashSHA256) }

func New224() *Hash { return newHash(hashSHA224) }

func New384() *Hash { return newHash(hashSHA384) }

func New512() *Hash { return newHash(hashSHA512) }
