// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by hashgen. DO NOT EDIT.

//go:build msgostd || cmd_go_bootstrap

package sha3

import (
	fallback "crypto/internal/fips140/sha3"
	"hash"
)

type fipsHash = fallback.Digest

func initFallback256() *fipsHash { return fallback.New256() }

func initFallback224() *fipsHash { return fallback.New224() }

func initFallback384() *fipsHash { return fallback.New384() }

func initFallback512() *fipsHash { return fallback.New512() }

func New256() *Hash { return newHash(hashSHA256) }

func New224() *Hash { return newHash(hashSHA224) }

func New384() *Hash { return newHash(hashSHA384) }

func New512() *Hash { return newHash(hashSHA512) }

// Unwrap returns the selected hash implementation.
func Unwrap(h *Hash) hash.Hash { return h.unwrap() }
