// Copyright (c) Microsoft Corporation.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:generate go run . -o ../../../doc/CrossPlatformCryptography.md crypto.json
//go:generate go run github.com/wasilibs/go-prettier/cmd/prettier@latest --write ../../../doc/CrossPlatformCryptography.md

package main

import (
	_ "embed"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

//go:embed header.md
var header string

type PlatformStatus struct {
	Supported         string   `json:"supported"`
	MinGoVersion      string   `json:"minGoVersion,omitempty"`
	Notes             []string `json:"notes,omitempty"`
	MinMacOSVersion   string   `json:"minMacOSVersion,omitempty"`
	MinOpenSSLVersion string   `json:"minOpenSSLVersion,omitempty"`
}

type Item struct {
	Name         string                    `json:"name"`
	MinGoVersion string                    `json:"minGoVersion,omitempty"`
	Notes        []string                  `json:"notes,omitempty"`
	Platforms    map[string]PlatformStatus `json:"platforms"`
}

type Section struct {
	Title             string    `json:"title"`
	ShortTitle        string    `json:"shortTitle,omitempty"`
	ColumnHeader      string    `json:"columnHeader,omitempty"`
	Packages          []string  `json:"packages,omitempty"`
	Description       string    `json:"description,omitempty"`
	MinGoVersion      string    `json:"minGoVersion,omitempty"`
	MinMacOSVersion   string    `json:"minMacOSVersion,omitempty"`
	MinOpenSSLVersion string    `json:"minOpenSSLVersion,omitempty"`
	Items             []Item    `json:"items,omitempty"`
	Subsections       []Section `json:"subsections,omitempty"`
	Footnotes         []string  `json:"footnotes,omitempty"`
	Footer            string    `json:"footer,omitempty"`
}

type Document struct {
	Sections []Section `json:"sections"`
}

func main() {
	output := flag.String("o", "", "output file path")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		fmt.Fprintf(os.Stderr, "Usage: %s [options] <path-to-json>\n", os.Args[0])
		os.Exit(1)
	}

	if *output != "" {
		f, err := os.Create(*output)
		if err != nil {
			panic(err)
		}
		defer f.Close()
		os.Stdout = f
	}

	data, err := os.ReadFile(args[0])
	if err != nil {
		panic(err)
	}

	var doc Document
	if err := json.Unmarshal(data, &doc); err != nil {
		panic(err)
	}

	if err := validate(doc); err != nil {
		fmt.Fprintf(os.Stderr, "Validation error: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("<!-- This file is generated by eng/_util/cmd/gencryptodoc. DO NOT EDIT. -->")
	fmt.Println()
	fmt.Println(header)

	for _, section := range doc.Sections {
		printSection(section, 2)
	}
}

func printSection(section Section, level int) {
	fmt.Printf("\n%s %s\n\n", strings.Repeat("#", level), section.Title)

	// Filter packages
	var validPackages []string
	for _, pkg := range section.Packages {
		if strings.Contains(pkg, "/") || strings.Contains(pkg, ".") {
			validPackages = append(validPackages, pkg)
		}
	}

	if len(validPackages) > 0 {
		fmt.Println("This section includes the following packages:")
		fmt.Println()
		for _, pkg := range validPackages {
			if strings.HasPrefix(pkg, "crypto/") {
				fmt.Printf("- [%s](https://pkg.go.dev/%s)\n", pkg, pkg)
			} else if strings.HasPrefix(pkg, "golang.org/") {
				fmt.Printf("- [%s](https://pkg.go.dev/%s)\n", pkg, pkg)
			} else {
				// Fallback
				fmt.Printf("- %s\n", pkg)
			}
		}
		fmt.Println()
	}

	// Prepend version requirements to description if present
	var versionSentences []string
	if section.MinGoVersion != "" {
		versionSentences = append(versionSentences, fmt.Sprintf("%s is available starting from the Microsoft build of Go %s.", section.Title, section.MinGoVersion))
	}
	if section.MinOpenSSLVersion != "" {
		versionSentences = append(versionSentences, fmt.Sprintf("%s requires OpenSSL %s or later.", section.Title, section.MinOpenSSLVersion))
	}
	if section.MinMacOSVersion != "" {
		versionSentences = append(versionSentences, fmt.Sprintf("%s is available starting in macOS %s (Tahoe) or later.", section.Title, section.MinMacOSVersion))
	}
	if len(versionSentences) > 0 {
		fmt.Println(strings.Join(versionSentences, " "))
		fmt.Println()
	}
	if section.Description != "" {
		fmt.Println(section.Description)
		fmt.Println()
	}

	// Subsections list
	if len(section.Subsections) > 0 {
		if section.Description == "" {
			fmt.Println("This section includes the following subsections:")
			fmt.Println()
		}
		for _, sub := range section.Subsections {
			// Generate anchor link
			anchor := strings.ToLower(sub.Title)
			anchor = strings.ReplaceAll(anchor, " ", "-")
			anchor = strings.ReplaceAll(anchor, "(", "")
			anchor = strings.ReplaceAll(anchor, ")", "")

			title := sub.Title
			if sub.ShortTitle != "" {
				title = sub.ShortTitle
			}
			fmt.Printf("- [%s](#%s)\n", title, anchor)

		}
		fmt.Println()
	}

	if len(section.Items) > 0 {
		printTable(section)
	}

	if section.Footer != "" {
		fmt.Println(section.Footer)
		fmt.Println()
	}

	for _, sub := range section.Subsections {
		printSection(sub, level+1)
	}
}

func printTable(section Section) {
	colHeader := section.ColumnHeader
	if colHeader == "" {
		colHeader = "Algorithm" // Default
	}

	fmt.Printf("| %s | Windows | Linux | macOS |\n", colHeader)

	// Separator line
	// I need to match the length of dashes if I want exact diff, but markdown doesn't strictly require it.
	// The original file had varying lengths.
	// I'll just use standard lengths.
	fmt.Println("| --- | --- | --- | --- |")

	// Collect footnotes
	footnotes := make(map[string]int)
	nextFootnote := 1

	// Pre-populate from section.Footnotes
	for _, note := range section.Footnotes {
		if _, exists := footnotes[note]; !exists {
			footnotes[note] = nextFootnote
			nextFootnote++
		}
	}

	// Helper to get footnote indices
	getFootnotes := func(notes []string) string {
		if len(notes) == 0 {
			return ""
		}
		var indices []int
		for _, note := range notes {
			idx, exists := footnotes[note]
			if !exists {
				idx = nextFootnote
				footnotes[note] = idx
				nextFootnote++
			}
			indices = append(indices, idx)
		}
		sort.Ints(indices)
		strs := make([]string, len(indices))
		for i, idx := range indices {
			strs[i] = fmt.Sprintf("%d", idx)
		}
		return fmt.Sprintf("<sup>%s</sup>", strings.Join(strs, ","))
	}

	for _, item := range section.Items {
		name := item.Name

		itemNotes := item.Notes
		if item.MinGoVersion != "" {
			note := fmt.Sprintf("Available starting in the Microsoft build of Go %s.", item.MinGoVersion)
			itemNotes = append([]string{note}, itemNotes...)
		}

		nameNotes := getFootnotes(itemNotes)

		row := []string{name + nameNotes}

		for _, platform := range []string{"windows", "linux", "macos"} {
			status := item.Platforms[platform]
			symbol := ""
			switch status.Supported {
			case "N/A":
				symbol = "N/A"
			case "true":
				symbol = "✔️"
			case "warn":
				symbol = "⚠️"
			default:
				symbol = "❌"
			}

			statusNotes := status.Notes
			// Prepend version notes in preferred order: minGoVersion, minOpenSSLVersion, minMacOSVersion
			var versionNotes []string
			if status.MinGoVersion != "" {
				versionNotes = append(versionNotes, fmt.Sprintf("Available starting in the Microsoft build of Go %s.", status.MinGoVersion))
			}
			if status.MinOpenSSLVersion != "" {
				versionNotes = append(versionNotes, fmt.Sprintf("Requires OpenSSL %s or later.", status.MinOpenSSLVersion))
			}
			if status.MinMacOSVersion != "" {
				versionNotes = append(versionNotes, fmt.Sprintf("Requires macOS %s or later.", status.MinMacOSVersion))
			}
			// Remove duplicates from notes
			filtered := []string{}
			for _, n := range statusNotes {
				duplicate := false
				for _, vn := range versionNotes {
					if n == vn {
						duplicate = true
						break
					}
				}
				if !duplicate {
					filtered = append(filtered, n)
				}
			}
			statusNotes = append(versionNotes, filtered...)

			notes := getFootnotes(statusNotes)
			row = append(row, symbol+notes)
		}

		fmt.Printf("| %s | %s | %s | %s |\n", row[0], row[1], row[2], row[3])
	}
	fmt.Println()

	// Print footnotes
	// Sort by index
	sortedNotes := make([]string, len(footnotes))
	for note, idx := range footnotes {
		sortedNotes[idx-1] = note
	}

	for i, note := range sortedNotes {
		fmt.Printf("<sup>%d</sup>%s\n\n", i+1, note)
	}
}

func validate(doc Document) error {
	for _, section := range doc.Sections {
		if err := validateSection(section); err != nil {
			return err
		}
	}
	return nil
}

func validateSection(section Section) error {
	if section.Title == "" {
		return fmt.Errorf("section missing title")
	}

	for i := range section.Items {
		item := &section.Items[i]
		if item.Name == "" {
			return fmt.Errorf("item missing name in section %q", section.Title)
		}
		if item.Platforms == nil {
			item.Platforms = make(map[string]PlatformStatus)
		}
		for _, p := range []string{"windows", "linux", "macos"} {
			status, ok := item.Platforms[p]
			if !ok {
				status = PlatformStatus{}
			}
			if status.Supported == "" {
				status.Supported = "true"
			}
			item.Platforms[p] = status
			switch status.Supported {
			case "true", "false", "warn", "N/A":
				// ok
			default:
				return fmt.Errorf("invalid supported status %q for item %q on platform %q", status.Supported, item.Name, p)
			}
		}
	}
	for _, sub := range section.Subsections {
		if err := validateSection(sub); err != nil {
			return err
		}
	}
	return nil
}
