name: Check Line Endings

on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read

jobs:
  check-line-endings:
    uses: microsoft/go-infra/.github/workflows/check-line-endings.yml@f4e3833067a0e64dbf9581e3e4d2df2a353f6dd0 # v0.0.13
