name: Check Line Endings

on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read

jobs:
  check-line-endings:
    uses: microsoft/go-infra/.github/workflows/check-line-endings.yml@ebf0f3b5830787f246af9866e867e75db5ff9753 # v0.0.16
