name: Check Line Endings

on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read

jobs:
  check-line-endings:
    uses: microsoft/go-infra/.github/workflows/check-line-endings.yml@d38578e09d4278d489388a659d65cc5c0ba6063b # v0.0.18
