name: golangci-lint
on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run golangci-lint
        working-directory: eng/_util
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.0 golangci-lint run -v
