name: golangci-lint
on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run golangci-lint
        working-directory: eng/_util
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.10 golangci-lint run -v
