name: golangci-lint
on:
  push:
    branches:
      - "microsoft/*"
  pull_request:
    branches:
      - "microsoft/*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run golangci-lint
        working-directory: eng/_util
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.0 golangci-lint run -v
