# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This job tests that each patch file is buildable (in numerical order)

name: "Patch Build"

on:
  pull_request:
    branches: [ microsoft/* ]

# Cancel existing runs if user makes another push.
concurrency:
  group: "${{ github.ref }}-${{ github.workflow}}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  list_patches:
    name: Generate patch build matrix
    runs-on: ubuntu-latest
    outputs:
      patches: ${{ steps.list.outputs.patches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Write patch matrix
        id: list
        run: pwsh eng/run.ps1 write-patch-matrix -github-actions

  build_patches:
    name: "Build up to ${{ matrix.patch.name }}"
    needs: list_patches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        patch: ${{ fromJson(needs.list_patches.outputs.patches) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true

      - name: Set mock git config name/email
        run: |
          git config --global user.email "joe@blogs.com"
          git config --global user.name "Joe Blogs"

      - name: Apply patches 1-${{ matrix.patch.number }}
        run: pwsh eng/run.ps1 submodule-refresh -commits -take ${{ matrix.patch.number }}

      - name: Build
        env:
          MS_USE_CI_STAGE0: 1 # Use the stage 0 Go version installed by the CI script, rather than the system-installed version of Go.
        run: |
          set -x
          pwsh eng/run.ps1 build
          cd ${{ github.workspace }}/go/src
          ${{ github.workspace }}/go/bin/go mod vendor
          cd ${{ github.workspace }}/go/src/cmd
          ${{ github.workspace }}/go/bin/go mod vendor
          cd ${{ github.workspace }}/go/src
          # Check if the vendor directory is clean
          git diff --exit-code vendor cmd/vendor || (echo "Vendor directories are not clean. Please run 'go mod vendor' in the appropriate directories and commit the changes." && exit 1)
