# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This job tests that each patch file is buildable (in numerical order)

name: "Patch Build"

on:
  pull_request:
    branches: [ microsoft/* ]

# Cancel existing runs if user makes another push.
concurrency:
  group: "${{ github.ref }}-${{ github.workflow}}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build_patches:
    name: Patches Build in Order
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Set mock git config name/email
        run: |
          git config --global user.email "joe@blogs.com"
          git config --global user.name "Joe Blogs"

      - name: Build patches
        run: |
          for file in $(ls -v patches/*.patch); do
            echo "::group::Building $file"
            cd ${{ github.workspace }}/go
            git am --whitespace=nowarn ${{ github.workspace }}/$file
            cd ${{ github.workspace }}/go/src
            bash make.bash
            ${{ github.workspace }}/go/bin/go mod vendor
            cd ${{ github.workspace }}/go/src/cmd
            ${{ github.workspace }}/go/bin/go mod vendor
            cd ${{ github.workspace }}/go/src
            # Check if the vendor directory is clean
            git diff --exit-code vendor cmd/vendor || (echo "Vendor directories are not clean. Please run 'go mod vendor' in the appropriate directories and commit the changes." && exit 1)
            echo "::endgroup::"
          done
