# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This job tests that the patches apply cleanly, and nothing else. The goal is to test this as
# quickly as possible. This job is a good signal for devs: GitHub Actions is quick to get an agent,
# so when this job fails, it's easy to see, and clear to the dev that the rest of the PR's jobs
# aren't going to succeed and can be ignored.
#
# Ideally, failure of this job would block the tests from running, because it would be a waste of
# time to hit the patch failure N times. However, the actual tests run in AzDO, so we can't
# reasonably cancel them from here (GitHub Actions).

name: "Test"

on:
  pull_request:
    branches: [ microsoft/* ]

jobs:
  check_patches:
    name: Patches Apply Cleanly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: pwsh eng/run.ps1 submodule-refresh -shallow
